### ISSUE TITLE
"iw3" can the custom depth map import be added?

### ISSUE THREAD

**Issue by SunQQi** [nagadomi/nunif#115]
I used models from other projects to generate depth maps and want to test the impact of different depth maps on the video, to see if it's possible to support animations.

**Comment by nagadomi** [comment]
iw3 already supports export and import of depth images, frame images, and audio.

See https://github.com/nagadomi/nunif/discussions/87 and https://github.com/nagadomi/nunif/issues/97

**Comment by SunQQi** [comment]
> iw3 already supports export and import of depth images, frame images, and audio.
> 
> See #87 and #97

Thank you, I will continue trying to use it
