### ISSUE TITLE
Unable to find GPU

### ISSUE THREAD

**Issue by 414726193** [nagadomi/nunif#117]
I ran iw3 on another computer with only cpu and no GPU in the Device, I actually had a 1050ti graphics card

**Comment by nagadomi** [comment]
If GPU is not listed, PyTorch failed to detect CUDA devices.

1. Have you installed the latest NVIDIA driver?
2. What OS are you using?
4. Are you using `nunif-windows-package`? Or a Python environment you built yourself?

In the past, there was a case that GPU is not shown in a mixed Anaconda environment. https://github.com/nagadomi/nunif/issues/74
