### ISSUE TITLE
error rendering iw3 un openable and un updatable!

### ISSUE THREAD

**Issue by donrikk** [nagadomi/nunif#134]
i went to update and i got a mile long string of trace back errors, says it cant find array api or something and it also mentions something about numpy 2 and downgrading to lower numpy version? as of current update i cant use the program though i tried uninstalling and re installing numpy with no luck. tried updating an older backed up version of iw3 still with no luck.

**Comment by donrikk** [comment]
i also installed nunif fresh and it still didnt work.

**Comment by nagadomi** [comment]
Same as https://github.com/nagadomi/nunif/issues/135
Fixed now.
