### ISSUE TITLE
Cuda error: invalid configuration argument

### ISSUE THREAD

**Issue by Fresinho2024** [nagadomi/nunif#136]
Hello Nagadomi, thank you so much for IW3. It is so cool to use 3D. May I know if I did something wrong when I installed the bat? Here are 3 screenshots.

![Screenshot 2024-06-17 000048](https://github.com/nagadomi/nunif/assets/173030947/04118aa8-d20c-4008-bdeb-076b8e38fe6b)
![Screenshot 2024-06-17 000302](https://github.com/nagadomi/nunif/assets/173030947/9563180f-0966-4770-b04f-604a010fde8d)
![Screenshot 2024-06-17 000421](https://github.com/nagadomi/nunif/assets/173030947/2d33c11d-4e9c-4176-89f0-24c22d587abb)

**Comment by nagadomi** [comment]
Does the same error occur for other models such as Any_S?
Could you clarify if it will not work in any setting or if it is only an error for a specific setting/input?

**Comment by nagadomi** [comment]
Fixed https://github.com/nagadomi/nunif/commit/376abaa2ed3f8bb6a2e8074db1f5c0ebd2c12644
