### ISSUE TITLE
Error: `/data/dataset/waifu2x/eval` not found

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#14]
![2023-03-26_19-54-36](https://user-images.githubusercontent.com/49092250/227791470-24f56256-79a3-485a-be5b-b2becc2c5cd1.png)

**Comment by nagadomi** [comment]
The following directory structure is required for the dataset.
```
/dataset/
├── train/
└── eval/
```
Also, I do not provide dataset.  If you want to train your model, you should create your own dataset.

**Comment by My12123** [comment]
![2023-03-26_20-45-01](https://user-images.githubusercontent.com/49092250/227794216-365380c4-b40b-4026-a40f-c33741a4927c.png)

**Comment by nagadomi** [comment]
Then specify that directory.
```
--dataset-dir .\dataset 
```
