### ISSUE TITLE
Can video files be used for the rgb and depth in the output directory structure to save hard drive space?

### ISSUE THREAD

**Issue by Alex12358** [nagadomi/nunif#145]
Can video files be used for the rgb and depth in the output directory structure to save hard drive space?
I need to process the movie and input custom depth video data, but converting to a sequence of frames is a significant performance overhead.

#97

**Comment by nagadomi** [comment]
It would be technically possible.
However, I don't know the proper video format for 16bit grayscale, so I think it is simpler to just buy a 4TB HDD.
If there is a video format for depth that is commonly used for VFX, etc., I may be able to support it.

Also, `Export` feature can significantly improve performance if `Max Threads`(`--max-workers`) is set to 16.

**Comment by SunQQi** [comment]
Got it, thank you for your response. Buying a 4TB hard drive is indeed a simple solution. If you could find a 16-bit grayscale video format suitable for depth data, I would greatly appreciate it.

Additionally, thank you very much for your suggestion about setting the maximum threads (--max-workers) to 16. I will try this method to improve performance.

I hope you can continue to improve this project. Thank you again for your help.
