### ISSUE TITLE
BIG PROBLEM! ALL V2 N and K DEPTH MODELS ARE COMPLETELY DESTROYED AS OF LATEST UPDATE.

### ISSUE THREAD

**Issue by donrikk** [nagadomi/nunif#146]
for some reason all maps inlovling v2 are now destroyed these are a few examples 
of a variety of models between any n v2 models and regular v2 small through large models now after the update. all of these examples are N v2 models just to clarify just differnt depth model sizes like base small and large 

![image](https://github.com/nagadomi/nunif/assets/106938990/5c78da04-4c73-4fca-a1f3-52189f9b924c)
![image](https://github.com/nagadomi/nunif/assets/106938990/c5864358-dbb0-45b7-8246-b684142c8c7e)
![image](https://github.com/nagadomi/nunif/assets/106938990/fd48c708-dd81-4b09-b8fe-9a5e5355e6d5)
![image](https://github.com/nagadomi/nunif/assets/106938990/fc7f81cb-76bd-41de-9bcf-ddc418bca9f3)
![image](https://github.com/nagadomi/nunif/assets/106938990/1f98d887-ea26-4409-808c-bf1bdcabca85)

**Comment by loawizard** [comment]
Is this normal?

**Comment by donrikk** [comment]
not even close to normal notice his hospital gown in the last example here. his entire shirt is being repreesented as extremely far background when it should be at least mid ground and that happens like every other depth frame so the chest is constatly bouncing in and out of foreground level. its def not performing properly i highly doubt this was the intended look for the map.

**Comment by nagadomi** [comment]
I suspect it is a known problem with V2 recognizing glass and mirrors as flat surfaces.
I have confirmed that it is the same result as the official code.

**Comment by donrikk** [comment]
@nagadomi yeah that i expect ive seen that and i tend to ignore it as at some point thatll get better but if u look at the example above his shirt not a glass surface or mirror just a regular shirt is being project to the background in black so in this example abov his torso is popping out of foreground and all the awy into the background leaving him as a floating head and arm. iobviously i dont think it has anythingto do with you but i do think the depth anything crew may have miss the mark on the accuracy of the map the majorty of frames look like water paint there is almost zer oacuracy at all in tyhe model which is weird becuase if any s is in it then it should at the very least have some foreground detal but it doesnt. i may have to try to see if i can some way inform the depth anything devs about this as i dont think they intended this map to do what its doing. im not expecting it to be the greeatest thing in the world but as of currently v1 N model is better than v2 and that fundementally makes no sense to me lol

**Comment by nagadomi** [comment]
may be related issue https://github.com/DepthAnything/Depth-Anything-V2/issues/10 https://github.com/LiheYoung/Depth-Anything/issues/201

**Comment by kaelsonofkrypto** [comment]
hi Nagadomi, something is definitely wrong with the any sv2 model in iw3, i just checked it compared to hugging face v1, v2, and iw3, for some reason the any sv2 has lost complete detail, here is a screen shot of them side my side
![broken any sv2](https://github.com/nagadomi/nunif/assets/164638883/e206e236-0d10-453f-8920-f216765d6427)

**Comment by kaelsonofkrypto** [comment]
here is the original source rgb i used

**Comment by kaelsonofkrypto** [comment]
https://drive.google.com/file/d/1N-CaueINcpr6USzKmTHQc9O9M8zucgYY/view?usp=sharing

**Comment by nagadomi** [comment]
@kaelsonofkrypto
Try the same settings as demo.
Depth Model = ANY_V2_S, Depth Resolution = 518, Foreground Scale = 0, Edge Fix = OFF
Export

**Comment by kaelsonofkrypto** [comment]
@nagadomi hi nagadomi, thanks to another members finding, he found what was broken apparently if u go past 518 on depth resolution for, any s, it degrades the quality and looks worse, but if u use any s v2 at 518 depth resolution it looks much better than on high depth res. The depth resolution in iw3 is broken past 518, here is a screenshot of iw3 any s v2 on the left at 1400 depth res and on the the right any s v2 at 1400 depth resolution


![image](https://github.com/nagadomi/nunif/assets/164638883/56670087-0987-4c4e-8868-9b3ad9b2a397)
