### ISSUE TITLE
New Any V2 N maps issue?

### ISSUE THREAD

**Issue by 3gMan** [nagadomi/nunif#147]
We are looking into it more, but there may be an issue with at least the small and base V2 N's? some examples below and in donrikk's separate post.

**Comment by loawizard** [comment]
![00000051](https://github.com/nagadomi/nunif/assets/153664373/37a8886b-5065-426f-b7ff-50ccd67bc659)
![00000055](https://github.com/nagadomi/nunif/assets/153664373/bcd51ad2-264c-4beb-8db2-e00f4418fc0c)
![00000073](https://github.com/nagadomi/nunif/assets/153664373/8e206db4-e439-4703-b5da-88b7f49eadb8)
![00000096](https://github.com/nagadomi/nunif/assets/153664373/937804aa-eb7f-47ee-b071-b20a3f544bc7)

here some of my examples

**Comment by nagadomi** [comment]
same as #146
