### ISSUE TITLE
Correct YUV(YCbCr/YPbPr) colorspace conversion for video processing

### ISSUE THREAD

**Issue by nagadomi** [nagadomi/nunif#164]
### Discussed in https://github.com/nagadomi/nunif/discussions/157

Maybe the current implementation uses BT.601 for yuv420p/yuv444p.
Since HD MP4 generally uses BT.709, the color conversion may not be correct.

Maybe color_range (pc/tv) is also related to this problem.

In this area, including the ffmpeg/pyav implementation, are a nightmare, so I am not sure whether this can be handled correctly.

**Comment by 3gMan** [comment]
This is what the double color space conversion does in iw3 when selecting yuv420p. RGB didn't seem much better for banding, but I didn't check actual colors like this.
![Screenshot (111)](https://github.com/nagadomi/nunif/assets/166266906/1c511d48-41d9-498a-b724-aef3f5eb1c71)
Original is left. Iw3 convert on right using yuv420p, slower, 15 crf.

**Comment by nagadomi** [comment]
I think the darker image on the right is due to the colorspace (this issue).

Also the boundary between the background and the person on the left side of the screen is visible as sharp edges. However, I think it is due to the stereo generation process and not related to colorspace or encoding. This seems to be the result of `forward_fill`.

**Comment by 3gMan** [comment]
> I think the darker image on the right is due to the colorspace (this issue).
> 
> Also the boundary between the background and the person on the left side of the screen is visible as sharp edges. However, I think it is due to the stereo generation process and not related to colorspace or encoding. This seems to be the result of `forward_fill`.

I agree it's the same issue. The sharp edges not sure. I used rowflow V3 exporting from iw3, but it could also be the specific camera method I am using in Resolve. Haven't noticed it while watching.

**Comment by romanr** [comment]
> Using iw3 dmap in resolve

How do you that, how do you get dmap, using command line? 
Do you use any camera footage as source?

**Comment by 3gMan** [comment]
> > Using iw3 dmap in resolve
> 
> How do you that, how do you get dmap, using command line? Do you use any camera footage as source?

"Export Disparity" under stereo format. This creates a png image for each depth frame which takes up a good amount of space. Select all dmap images, and drag onto timeline in Resolve. You can then delete that timeline video, and you are left with a fully usable depthmap clip in the "media" tab of resolve.

**Comment by romanr** [comment]
> depthmap clip

Do you use Fusion and 3D camera to achieve final SBS video?

**Comment by 3gMan** [comment]
> > depthmap clip
> 
> Do you use Fusion and 3D camera to achieve final SBS video?

Yes sir!

**Comment by nagadomi** [comment]
I added `Colorspace`(--colorspace) option. The default is `unspecified`, which is the same as the previous versions that does nothing. 
See https://github.com/nagadomi/nunif/blob/dev/iw3/docs/colorspace.md for details.
This is a very complicated feature. (and sorry for my english skills for this complicated spec)
I wanted `auto` to be the default value, but I am not very confident that it works correctly with any video.

Please let me know if you have any problems, errors, or questions about this feature.

**Comment by romanr** [comment]
This is good that bt709 is added! Having only bt709 SDR makes little sense though,  I think colour space support is needed for HDR primarily. Having only bt709 does not really make difference.
