### ISSUE TITLE
Setting the GPU via command line

### ISSUE THREAD

**Issue by sundriftproductions** [nagadomi/nunif#170]
Hello --

I recently discovered IW3 and think it's great. I've been using the GUI version and have been very pleased with the speed with rendering off of my video card.

Now I'm trying to come up with a command line to do the exact same thing that I usually do in the GUI. Here is an example of what I'll use in the GUI:

![image](https://github.com/nagadomi/nunif/assets/11555816/b0309bef-8ac4-476d-a103-c86ba371441f)

And here's what I think is the equivalent CLI version:

`python -m iw3 --input "M:\junk\actually convert these\test 1.avi" --output "M:\junk\actually convert these\test 1_SBS.mp4" --divergence 2.0 --convergence 0.5 --method row_flow_v3 --depth-model Any_V2_N_B --foreground-scale 0 --max-fps 30 --crf 20 --preset ultrafast --video-format mp4 --pix-fmt yuv420p --zoed-batch-size 2 --max-workers 16 --tta --ipd-offset 0 --edge-dilation 0 --gpu 0`

The problem, though, is the `--gpu 0` part. If I leave it off, it _appears_ that it's relying on the CPU to render. (Please correct me if I'm wrong about this.) If I leave it on, my understanding is that this is supposed to pick up the first GPU it can find. Instead, I get this:

![image](https://github.com/nagadomi/nunif/assets/11555816/3d60d57e-157f-4616-a1c4-e5427fa13df3)

Any idea how I can fix this? I'd really like to render off of the GPU, not CPU via the command line.

**Comment by nagadomi** [comment]
The use of `--gpu` option is not a problem.

I am guessing the problem is that Python environment used for CLI is different from GUI. (installed PyTorch version does not support CUDA)
If you have installed the GUI with `nunif-windows-package`, try the CLI on a prompt launched from `nunif-prompt.bat`.

If you want to create a python (venv) environment manually, the following command should install the same modules as `nunif-windows-package`.
```
pip install --no-cache-dir --upgrade -r requirements-torch.txt
pip install --no-cache-dir --upgrade -r requirements.txt
# pip install --no-cache-dir --upgrade -r requirements-gui.txt
```

This seems to be the same problem of #74 and CLI/GUI just reversed.

**Comment by sundriftproductions** [comment]
Thank you, nagadomi! Launching `nunif-prompt.bat` first works.

If I were to run the `pip install` commands that you mentioned, would the GUI version still work?

**Comment by nagadomi** [comment]
Is using CLI from `nunif-prompt.bat` not suitable for your purposes?

`nunif-windows-package` has a built-in python environment that is not affected by system python or other python projects. 
`nunif-prompt.bat` sets environment variables for its built-in python environment before launching the command prompt.

Running the above `pip install` command from global/system python will not affect `nunif-windows-package` environment, but if you are using other python projects, it can break their dependencies.
In practice, `venv` is used to avoid such problems.

**Comment by sundriftproductions** [comment]
Ah, that makes sense. I can work with the CLI from `nunif-prompt.bat`. Thank you for clarifying, nagadomi!
