### ISSUE TITLE
Slow video

### ISSUE THREAD

**Issue by beatet** [nagadomi/nunif#175]
Hi, fantastic program. You are the best!!
In some conversions with BDRemux quality movies, the result is like the movie is in 15fps. It happens sometimes but if I do the same with a 4k source it´s ok. I would do all the conversions with 4k but it is very slow. I think the best quality/speed ratio is with BDRemux.
Do you know what is the problem?  

Thanks in advance

**Comment by nagadomi** [comment]
Does **15fps** mean the processing speed of the conversion? or the playback FPS of the output video?
Also, what is BDRemux? Is it 1080p m2ts file?

**Comment by nagadomi** [comment]
I still don't fully understand the problem, but this may be related to Interlaced video.
Try Deinterlace=yadif.

Also I added .m2t, .mts alias for ts format and fixed a problem with very long progress bar when exporting ts file.

**Comment by beatet** [comment]
It is the the playback FPS of the output video. 
BDremux is when you rip a bluray without losing quality

**Comment by beatet** [comment]
I will try yadif.
Thank you for the answers

**Comment by nagadomi** [comment]
If this issue was resolved or if you are not interested in this issue, I will close this issue.

If you still can't resolve the issue, could you please post information about the video container and codec? That can be viewed with MediaInfo.
