### ISSUE TITLE
Is it possible to get rid of graininess?

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#18]
![2023-03-27_21-24-18](https://user-images.githubusercontent.com/49092250/228032775-21ea14c6-ae29-4625-a2f4-7de953dd057d.png)
![004 png_res](https://user-images.githubusercontent.com/49092250/228033109-392949c9-62bf-4605-a043-054794e15d9d.jpg)

**Comment by My12123** [comment]
Can you tell me when art model can be?

**Comment by nagadomi** [comment]
not planning now.

**Comment by nagadomi** [comment]
I am currently developing `art_scan` model.
It is primarily aimed for scanned art images, denoising  for scanned manga or  magazine, anime screen captures, restoring screentones, etc.
The skin and outfit areas in the above image can be denoised. background is preserved.

I will release it in the next few days.

**Comment by nagadomi** [comment]
I have released art_scan model. Try it.
