### ISSUE TITLE
Arm Support

### ISSUE THREAD

**Issue by Jothsa** [nagadomi/nunif#19]
Is there any way to get this to work on Arm devices (specifically a raspberry pi 4)? I have managed to install everything, but when I try to run any of the commands I receive this error.
```bash
38555 illegal hardware instruction  python3 -m waifu2x.web.webgen.gen
```

I'm using 64 bit raspbian, and am inside a virtual environment. My python is version 3.9.2

**Comment by nagadomi** [comment]
I am not familiar with Raspberry Pi.
My first thought, the reason for the error is that PyTorch uses AVX/AVX2.
I recently wrote steps to build pytorch without AVX in the following Dockerfile. (Note that this even disables CUDA)
https://github.com/nagadomi/nunif/blob/master/Dockerfiles/Dockerfile.cpu_noavx
At that time, I read various blog posts about building PyTorch for Raspberry Pi.

However, I just searched and found that PyTorch supports aarch64, which is described in the official PyTorch article.
https://pytorch.org/tutorials/intermediate/realtime_rpi.html

I am sure that one of the pip modules uses instructions that are not supported by that CPU, but I don't know which one.

I think you should check the following.
1. Is pytorch working well?
2. which line is causing the error

For 2, I configured the faulthandler to detect C-level errors but it doesn't seem to be working.

https://github.com/nagadomi/nunif/blob/c4ef47f220d8b4e4e4af1909bd20dd67f9f2055d/waifu2x/web/server.py#L456-L460

Maybe it is crashing at module import time before main function.

**Comment by Jothsa** [comment]
Thanks! I’ll check it out, but I might not have time until this weekend. I’ll keep you posted

**Comment by nagadomi** [comment]
This error is a bug in the pytorch aarch64 binary.
Just importing torch crashes.
```bash
$ python
Python 3.9.16 (main, Mar 30 2023, 13:22:28) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import torch
Illegal instruction
```
pytorch developers are currently working on this error.
https://github.com/pytorch/pytorch/issues/97226
