### ISSUE TITLE
Gift for waifu2x project!

### ISSUE THREAD

**Issue by unit2x** [nagadomi/nunif#191]
Hi, I'm a fan of your waifu2x project and noticed you're using waifu2x.net. I've owned the **waifu2x.com** domain for a while now after winning it in a domain auction. I haven't been able to put it to good use, though. I'd be happy to give it to you. If you're interested, please let me know how I can best reach you to provide the transfer code.

**Comment by nagadomi** [comment]
Not interested.
I have owned waifu2x.net since before waifu2x was released, but have not used it for a long time.
The reason I started using waifu2x.net recently is because I had GDPR related problems with udp.jp.
I just hope that the name waifu2x will not be used for malicious purposes.

**Comment by nagadomi** [comment]
This may sound heartless, but I have ignored or rejected everyone who has offered me a deal.
I remember that you are really a waifu2x user.
