### ISSUE TITLE
Is it possible to support compression support without loss in iw3?

### ISSUE THREAD

**Issue by cynodesmus** [nagadomi/nunif#196]
I, more recently, use your program. This is really a fantastic product.
And, I want to know: is it possible to add the support of lossless encoder "Ut Video"?
https://github.com/umezawatakeshi/utvideo
This encoder is supported by FFMPEG.
The question is related to the fact that coding in x264 sometimes gives out strange results, sometimes the bitrate is very underestimated, despite the higher CRF settings. Also, my equipment for viewing, does not perceive the profile high@l5.1 and, in any case, I have to carry out a re -encoding of the video stream.
The use of the UT Video encoder would reduce the volume of intermediate data and conduct subsequent coding with other software products.
The command line syntax for coding is minimal (unlike numerous settings x264). But, I don’t understand how it is realized in Python. Support in FFMPEG was mentioned (for example) here: https://video.stackexchange.com/questions/27685/how-to-use-magicyuv-utvideo-codec-with-ffmpeg
P.S. Once again, many thanks, for your program.

**Comment by nagadomi** [comment]
I considered using utvideo as a lossless encoder for Export before, but DaVinci Resolve didn't support it, so I didn't.
It is possible to use utvideo instead of h264. But is CRF=0, tune=grain/psnr not good enough?

utvideo and h264 have different encoding setting fields(GUI and internal setting fields), so it is probably easier to fix h264 setting issues. I can add `profile` option.
Also, currently most of the options use --x264-params, which may be the reason why the encoded video is different from ffmpeg command.

**Comment by cynodesmus** [comment]
As it was said here: https://forum.blackmagicdesign.com/viewtopic.php?f=33&t=132844  Davinci Resolve understands any video codec that is installed in the system.
In order for Windows to freely support the utvideo codec, you need to install the codec installer, which is on the developer's github - https://github.com/umezawatakeshi/utvideo/releases
In principle, additional installation of a codec into the system is standard practice. One can recall the times of the reign of lossy codecs DivX and ХviD...
utvideo is much faster in editing. And, as it seems to me, faster in the initial encoding of video than x264 сrf0
The basic syntax for encoding utvideo in ffmpeg is to specify "utvideo" as the encoder. As stated here: https://gist.github.com/AbsoluteDestiny/ac0551a32646d39b62d773b416737bfc
"UTVideo, being lossless, can generally handle any input format, so the command is simply:
_-c:v utvideo_"

On the command line it is:
_ffmpeg -i input.mkv -c:v utvideo -an outputFile.avi_

In any case, you are right.
I cannot judge which option is more optimal and easier to implement.
My opinion is that of an amateur and I see only the tip of the iceberg, so it seemed to me that the "checkbox" in the GUI and a few lines with a change of encoder is a simpler option.

If we touch on the x264 settings, then in this case the question concerns additional settings "profile" and its "level". Since the automatic settings are sewn by default, they choose the best option for encoding, but do not take into account the technical capabilities of the end user's device.

**Comment by nagadomi** [comment]
I tried to add `profile` and `level` options, but pyav doesn't seem to have a way to set h264 profile. It will be `Constrained Baseline` in most cases. `level` can be set, but I decided not to add this option at the moment.

**Comment by nagadomi** [comment]
I added `Video Format = avi`. It is utvideo.
video codec is
yuv420p: ULY0
yuv444p: ULY4
rgb24: ULRG

audio codec is copied if possible or aac if re-encoding is required. I tried flac(lossless audio) but it crashes on windows media player.

**Comment by nagadomi** [comment]
About h264 profile, I tried {“profile”: “high”},{“profile:v”: “high”},{“vprofile”: “high”},{“h264_profile”: “high”},{“x264-params”: “profile=high”} etc, but they are all ignored. 
I think I need to change the pyav code and compile it(it is Cython project). So I can't support it on my side.

**Comment by cynodesmus** [comment]
I apologize that I opened the request again, but I thought a little about what you said earlier about the profile and levels in x264.

As far as I understand the information from Wikipedia, the standard formed the basis of Blu-ray is limited by the maximum frame resolution, frame rate and maximum bitrate. For Blu-ray, this corresponds to "High@4". The level parameter, just imposes all these restrictions, which allows the decoder to understand and process the incoming video stream. Therefore, the hardware Blu-ray players (which are limited in their power) designed only for the main standard - may not cope with playing files encoded in "High@ 5.1" (which I received at the exit of iw3).

If, when encoding, it is possible to set a level parameter and it will be used by an encoder, it will probably allow you to play a file for a larger number of equipment, avoiding transcoding video files in other programs.

P.S. Support for Utvideo works without complaints.
If you think this request is excessive - please close it. The last time I hurried with the closure, thereby interrupting the discussion.
Thank you for improving your program and caring for users.

**Comment by nagadomi** [comment]
From my understanding(I am not familiar with h264 standard):
`level` has limits: `bit rate`, `resolution`, and `frame rate` (and MacroBlock, ake MB). If `level` is not specified, the appropriate `level` is automatically selected from the `resolution` and `frame rate` criteria.
libx264 codec does not automatically limit the `resolution` and `frame rate`. It is a user-specified setting.
If you specify a force low `level`(e.g, -level 3.0), ffmpeg will give you a warning message. (pyav probably suppresses it).
```
[libx264 @ 0x5bec1aa96ac0] frame MB size (240x68) > level limit (1620)
[libx264 @ 0x5bec1aa96ac0] DPB size (4 frames, 65280 mbs) > level limit (0 frames, 8100 mbs)
[libx264 @ 0x5bec1aa96ac0] MB rate (489600) > level limit (40500)
```
So even if you specify a low level, there is still a possibility that the hardware decoder cannot handle it.
It is possible that some implementations may simply make an error for higher levels that are unsupported. But in my experience, it is often `resolution` and `frame rate` limitation.

If you want the conversion result of a FHD source to be `level 4`, select `Half SBS` then the output will also be FHD and `level 4` should be automatically selected.

---

My concern about profile and level is the suspicion that it is limiting the `bit rate`. For when the user wants to use a higher level.

**Comment by cynodesmus** [comment]
I use Half TopBottom, but the output file is obtained with a level of 5.1
5.1 - excess value. Therefore, I wondered how to lower the level to exclude an unpleasant moment. If suddenly the video is not able to play.
Unfortunately, I am also not a specialist in the coding of the video, so most ideas may not be true.
But, having the opportunity to encode without losses, you can subsequently encode in any desired format. Simply, another step in the list of tasks performed but this is not critical.
I do not think that this issue is worth the additional cost of the solution.
Thank you.

**Comment by nagadomi** [comment]
I added `Level` option.
Note that this will probably only change the stream metadata. No warnings if the video is out of level specs.

I tried Half TB for FHD (1080p) and the level was 4.0. With 60FPS, it was 4.2.
If libx264 selects level 5.1, I think there is a some reason to use it.

I also found that h264 profile is `Constrained Baseline` when `preset=ultrafast` and `High` otherwise.

**Comment by cynodesmus** [comment]
Well, probably this will be one of the features that should be taken into account.
In any case, now it was possible to get the desired profile and level, choosing the necessary settings.
