### ISSUE TITLE
my 3d is backwards in the words of the clips

### ISSUE THREAD

**Issue by andy500** [nagadomi/nunif#197]
how can your program create the words in the video clip back to front in every frame can your program reprogram itself and don't think l say it likely ?

**Comment by nagadomi** [comment]
Front and back cannot be swapped. Because the real world doesn't see that.
If iw3 results look like that, then there is a bug in your video player/device. The right and left eyes are reversed.

**Comment by andy500** [comment]
it is not the  video player/device this is the link
https://drive.google.com/file/d/1HSrlO4GGzgeLtjUtDjWknxaQg-mcJAHN/view?usp=drive_link

**Comment by nagadomi** [comment]
Please provide examples in public.
I will not check that link.

**Comment by andy500** [comment]
every word in this video is in reverse not the people  and it is not a video player/device issues and l can not create it again you program as create a one of video that is in possible to create in 30min which is what your program you would need to see the video to understand it

**Comment by nagadomi** [comment]
I never request permission to access the file. because of security reasons.

Does `WORD` mean subtitle?
If so, that is depth model issue and is not currently supported.

**Comment by andy500** [comment]
no it is not  subtitle issues it is just thet every frame with a word in it is in reverse every street name in the move is in reverse every word what ever it is on is in reverse l never seen a video like it

**Comment by nagadomi** [comment]
Do you mean that all frames are horizontally flipped? And the original video is not.
![hflip](https://github.com/user-attachments/assets/101d61c9-5d8c-4c07-8daa-f4e095c52406)

**Comment by andy500** [comment]
sorry no just every word on every thing in the movie is in reverse

**Comment by nagadomi** [comment]
Could you post a screenshot?

**Comment by diverswan9** [comment]
@andy500 in your google-drive for the file under 'share' / 'share' change the 'General Access' from 'Restricted' to 'Anyone with the link'

**Comment by andy500** [comment]
ok and thank you for your new update much faster to convert to 3d one question do l need anything v-2_L model Python code all can l use the python code in the pretrained_models hub

**Comment by diverswan9** [comment]
His 'source file' is flipped so everything is like in a mirror but the 3d is correct. So @andy500 wants to 'flip' the source file before the 3d processing happens. Maybe a filter setting? 

@nagadomi , which reminds me... do the filter settings in '-vf (src) happen before or after 3d processing?

**Comment by diverswan9** [comment]
@andy500  enter hflip into filter settings in '-vf (src). This will horizontally 'flip' the source video.

**Comment by nagadomi** [comment]
@diverswan9 --vf is an option for the input video stream. It is applied before depth estimation. hflip should resolve this issue as you say.

**Comment by diverswan9** [comment]
> @diverswan9 --vf is an option for the input video stream. It is applied before depth estimation. hflip should resolve this issue as you say.

Yeah, I just found that out by testing hflip. Thanks!

**Comment by diverswan9** [comment]
>  one question do l need anything v-2_L model Python code all can l use the python code in the pretrained_models hub

The Depth_Anything_V2 models need to be manually downloaded and put in 'Checkpoints' folder.

         \nunif-windows\nunif\iw3\pretrained_models\hub\checkpoints

[https://huggingface.co/depth-anything](url)

**Comment by andy500** [comment]
l put The Depth_Anything_V2 models in the Checkpoints folder is that all l need

**Comment by diverswan9** [comment]
> l put The Depth_Anything_V2 models in the Checkpoints folder is that all l need to do no l did not use vf setting that how it come out

The V2 models should show up now in 'Depth Model'.

To get your video to 'display' the correct way enter **hflip**  in '-vf' box before processing. For some reason your 'source' video is horizontally flipped.

**Comment by andy500** [comment]
no more problems just did another clip come out ok thanks l had to add the V2 models in the gui did not show in Depth Model after restart the program but does now

**Comment by andy500** [comment]
Awesome, thanks for the update nagadomi
