### ISSUE TITLE
Waifu2x not available argument for training

### ISSUE THREAD

**Issue by SandraPapo** [nagadomi/nunif#20]
python3 train.py waifu2x       
usage: train.py [-h] {imagenet} ...
train.py: error: argument {imagenet}: invalid choice: 'waifu2x' (choose from 'imagenet')

I am following the documentation for training and when I run the help command it tells me waifu2x is an invalid choice.

**Comment by nagadomi** [comment]
I have fixed that problem at be3faf08d2e1939474a84a55530ec4e70d5234a2 (2023-02-07).
Perhaps the source code is out of date. git pull it again.
