### ISSUE TITLE
GTX1650 Not Actually Processing

### ISSUE THREAD

**Issue by Pipes59** [nagadomi/nunif#200]
Hi there. I'm running Windows 11 with a GTX1650 card and IW3 discovers it without a problem. However, the end video is SBS, there is no 3D effect. If I run the same settings with CPU processing only, the video comes out great with full 3D effects. Although, the processing is slow as molasses.  This leads me to believe it is GPU related. I looked through and changed a few things in the GeForce set up to no avail. Any help would be appreciated.

**Comment by Pipes59** [comment]
I got it to work. Deselecting FP16 has solved the problem as well as speeded things up by 2.5X.

**Comment by nagadomi** [comment]
That's good to hear.
GTX1650 does not have Tensor Cores, so FP16 has no advantage.

Maybe it is a problem with fp16 and flash attention.
I have GTX 1050Ti which is even older than GTX1650, so I will check it later.

**Comment by nagadomi** [comment]
I tried combinations of FP16, FP32, ZoeDepth, DepthAnything on my GTX1050Ti and all worked fine.
Maybe you need to update GPU driver
Either way FP16 on older GPUs is not recommended, though.

**Comment by Pipes59** [comment]
Here are the settings that caused the non-processed result, except for the FP16 not been ticked. It appears to work until you play back the outputted file.
![IW3Working](https://github.com/user-attachments/assets/64f254f9-a252-4f3d-909c-e1b8d16e404d)

**Comment by nagadomi** [comment]
It is possible that Flicker Reduction=0.99 is the cause. 
Flicker reduction=0.99 has the known problem that the 3D effect is lost for several seconds when the scene changes.

**Comment by Pipes59** [comment]
Thank you for the help. Issue closed.

**Comment by nagadomi** [comment]
I added a note to the README about older GPUs and FP16.
