### ISSUE TITLE
Support Custom FFmpeg Encoding Parameters in iw3 CLI （e.g specific using libx265)

### ISSUE THREAD

**Issue by TheRainstorm** [nagadomi/nunif#203]
Thanks for this great project! I noticed that iw3 defaults to H.264 encoding, which results in very high bitrates for 4K Full SBS videos. This causes stuttering and pixelation when playing back on my VR headset (Pico 4). Manually converting to H.265 (CRF 20) using ffmpeg fixes the issue, but it's an extra step.

Is it possible for iw3 CLI to generate h265 video directly? It may also help decreasing the video size.

**Comment by nagadomi** [comment]
Added support for libx265 https://github.com/nagadomi/nunif/commit/f5ded9073ab089e73138744f911d0bbb6f350e30 

For `iw3.cli`, you can use `---video-codec libx265` option to output in h265/hvec.
I have not tested enough, so let me know if there are any problems.

**Comment by nagadomi** [comment]
Also, iw3 defaults to `preset=ultrafast`, you can reduce the file size by specifying `--preset medium` option.

**Comment by TheRainstorm** [comment]
> For `iw3.cli`, you can use `---video-codec libx265` option to output in h265/hvec.

Thank you for your reply. However, I encountered an issue. I used to run the command with python -m iw3. Now, when I try to run it with python -m iw3.cli, I get an argument error. I pulled the latest master branch. Could you help me understand what I did wrong?

```shell
(iw3) ➜  python -m iw3.cli -i /path/to/input -o /path/to/output  --max-fps 128 --preset medium -g 0 ---video-codec libx265
usage: cli.py [-h] --input INPUT --output OUTPUT [--gpu GPU [GPU ...]]
              [--method {grid_sample,backward,forward,forward_fill,row_flow,row_flow_sym,row_flow_v3,row_flow_v3_sym,row_flow_v2}]
              [--divergence DIVERGENCE] [--convergence CONVERGENCE] [--update] [--recursive] [--resume] [--batch-size {1 <= value <= 256}]
              [--zoed-batch-size {1 <= value <= 64}] [--max-fps MAX_FPS] [--profile-level PROFILE_LEVEL] [--crf CRF]
              [--preset {ultrafast,superfast,veryfast,faster,fast,medium,slow,slower,veryslow,placebo}]
              [--tune {film,animation,grain,stillimage,psnr,fastdecode,zerolatency} [{film,animation,grain,stillimage,psnr,fastdecode,zerolatency} ...]]
              [--yes] [--pad PAD]
              [--depth-model {ZoeD_N,ZoeD_K,ZoeD_NK,Any_S,Any_B,Any_L,ZoeD_Any_N,ZoeD_Any_K,Any_V2_S,Any_V2_B,Any_V2_L,Any_V2_N,Any_V2_K,Any_V2_N_S,Any_V2_N_B,Any_V2_N_L,Any_V2_K_S,Any_V2_K_B,Any_V2_K_L}]
              [--remove-bg] [--bg-model BG_MODEL] [--rotate-left] [--rotate-right] [--low-vram] [--keyframe] [--keyframe-interval KEYFRAME_INTERVAL]
              [--vf VF] [--debug-depth] [--export] [--export-disparity]
              [--mapper {auto,pow2,softplus,softplus2,div_6,div_4,div_2,div_1,none,mul_1,mul_2,mul_3,inv_mul_1,inv_mul_2,inv_mul_3}]
              [--foreground-scale {-3,-2,-1,0,1,2,3}] [--vr180] [--half-sbs] [--tb] [--half-tb]
              [--anaglyph [{color,gray,half-color,wimmer,wimmer2,dubois,dubois2}]] [--pix-fmt {yuv420p,yuv444p,rgb24,gbrp}] [--tta] [--disable-amp]
              [--max-output-width MAX_OUTPUT_WIDTH] [--max-output-height MAX_OUTPUT_HEIGHT] [--keep-aspect-ratio] [--start-time START_TIME]
              [--end-time END_TIME] [--zoed-height ZOED_HEIGHT] [--stereo-width STEREO_WIDTH] [--ipd-offset IPD_OFFSET] [--ema-normalize]
              [--ema-decay EMA_DECAY] [--edge-dilation [EDGE_DILATION]] [--max-workers {0,1,2,3,4,8,16}] [--video-format {mp4,mkv,avi}]
              [--video-codec VIDEO_CODEC] [--metadata [{filename}]]
              [--find-param {divergence,convergence,foreground-scale,ipd-offset} [{divergence,convergence,foreground-scale,ipd-offset} ...]]
              [--colorspace {unspecified,auto,bt709,bt709-pc,bt709-tv,bt601,bt601-pc,bt601-tv}]
cli.py: error: unrecognized arguments: ---video-codec libx265
```

**Comment by diverswan9** [comment]
![2024-08-16_121258](https://github.com/user-attachments/assets/be5f29b7-56a4-41a0-97bb-3343585dba72)

**Comment by TheRainstorm** [comment]
> you can reduce the file size by specifying `--preset medium` option

The file size does decrease. Here’s the data (Original video is at 3840x2160@60, duration is 00:01:00, and the generated full SBS video is at 7680x2160@60):

- Default h264: 933 MB
- h264 with preset "medium": 449 MB (artifacts reduced but still present)
- h265 with preset "medium": 275 MB (no artifacts when playback)

**Comment by diverswan9** [comment]
> @diverswan9 Does that error always occur with other videos or any options? I guess some incompatible option is being used, but I have no idea which one.


I'll check... ahh! I had 'level' set at 4.1 for x264. Put it on 'auto' and worked fine... thanks!

**Comment by nagadomi** [comment]
@diverswan9 
It seems that libx265 causes the error if the size of the video is out of level spec. It is more strict than libx264.

**Comment by nagadomi** [comment]
I added notes to the README about H.265 level problem and the large file size problem.

https://github.com/nagadomi/nunif/tree/master/iw3#video-codec
https://github.com/nagadomi/nunif/tree/master/iw3#large-video-file-size
