### ISSUE TITLE
Keyerror 6

### ISSUE THREAD

**Issue by Pipes59** [nagadomi/nunif#205]
I've been converting videos with IW3 for a while with good results, but this error just popped up. It will not go away. I've tried update, restarting PC with no joy as error still persists. Any ideas?
![keyerror 6](https://github.com/user-attachments/assets/3cbf20ef-dab1-4112-a547-ed88eea61f23)

**Comment by nagadomi** [comment]
1. Run `nunif-prompt.bat`
2. Type `python -m iw3.gui` and press Enter
3. (iw3 GUI is launched)

![screen](https://github.com/nagadomi/nunif/assets/287255/6f0781ec-de59-4391-8a0c-d21f85e38e16)

Then, the full error message will be shown on the command prompt window.

**Comment by Pipes59** [comment]
I did as requested above, and the GUI starts. However, when I "start" the converter, the error pops up. This is when I get the keyerror. Program starts up fine. This is what is shown in the CMD window.
![IW3Working](https://github.com/user-attachments/assets/8d9c40ea-e3f1-4086-8271-10ba084984fd)

**Comment by Pipes59** [comment]
I found the problem. The video I was trying to convert was a .m4v which plays fine as a 2D video. It must be a compatibility issue. Thanks for your time.

**Comment by nagadomi** [comment]
This looks like a colorspace conversion issue.
You may avoid this error by specifying `Colorspace=unspecified`.

Could you post the mediainfo or ffprobe results for this video?
Only information about the colorspace is needed.
```
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709
```

**Comment by nagadomi** [comment]
In pyav, `6` is not defined as a colorspace value. (6 is maybe SMPTE170M)
I will fix this case.

**Comment by Pipes59** [comment]
![colour](https://github.com/user-attachments/assets/85c2707c-45ce-46b3-b69e-3c12c110835c)

**Comment by nagadomi** [comment]
Thank you. I can reproduce the error on my side.
At the moment, you can avoid this error by specifying `Colorspace=unspecified`.

**Comment by nagadomi** [comment]
Fixed. Run `update.bat` and try again.

**Comment by Pipes59** [comment]
Running as advertised. Thank you for your hard work.
