### ISSUE TITLE
Is it possible to increase GPU usage during training?

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#21]
![2023-03-30_11-07-16](https://user-images.githubusercontent.com/49092250/228782130-d16a8237-fc0b-4e29-814d-bab399057da0.png)
Command to run python train.py waifu2x --method scale --arch waifu2x.upcunet --data-dir F:\nunif\dataset --model-dir ./models/waifu2x_mymodel --num-workers 0

**Comment by nagadomi** [comment]
Basically, slower image loading reduces GPU utilization.

1. Do not use `--num-workers 0`. This slow down image loading and reduces GPU utilization.
2. Use fast SSD for `--data-dir`

In my env, it takes about 6 minutes per epoch for that setting.

**Comment by My12123** [comment]
The CPU is used the most. Is it possible for the GPU to be used the most?

**Comment by My12123** [comment]
The disk is not used during processing --datadir F:\nunif\dataset
![2023-03-30_12-12-04](https://user-images.githubusercontent.com/49092250/228788637-47fd8d57-204c-4c27-85e5-a429668b31a4.png)

**Comment by nagadomi** [comment]
It seems that GPU utilization by CUDA is not displayed in that area of Task Manager.
See this blog
https://michaelceber.medium.com/gpu-monitoring-on-windows-10-for-machine-learning-cuda-41088de86d65
And if CUDA option is not available, see  https://answers.microsoft.com/en-us/windows/forum/all/cuda-not-in-task-manager/a65eed92-828f-4d92-b9c9-cb2666bdd87f

(I have not checked because I do not have a Windows machine with CUDA.)

**Comment by My12123** [comment]
![2023-03-30_15-58-21](https://user-images.githubusercontent.com/49092250/228843436-ceedcfec-2df0-400d-9281-ed35c1c51434.png)
![2023-03-30_15-59-48](https://user-images.githubusercontent.com/49092250/228843852-5a2c84a0-bd31-4f47-8ba4-46682e8f8f42.png)
Even in Nvidia, the loading rate does not increase by 30%. How to fix it?

**Comment by nagadomi** [comment]
This depends on the machine spec.
Generally, increasing `--num-workers` and `--prefetch-factor` or `--batch-size`.
```
---num-workers 8
```
```
---num-workers 8 --prefetch-factor 8
```
```
---num-workers 8 --batch-size 32
```

Also, there are also known issues on Windows that do not perform for various reasons.
https://github.com/pytorch/pytorch/issues/22083

**Comment by My12123** [comment]
![2023-03-31_13-15-50](https://user-images.githubusercontent.com/49092250/229093357-b9c17432-f43d-475d-9e77-87e9d3494a71.png)
Thank you it helped

**Comment by nagadomi** [comment]
If loading images is still slow, you can also create smaller splitted image data by specifying `--size 320` option in `create_training_data.py`. 
It is default 640 (640x640 px), but should run without error even with 320 (320x320 px).

example
```
python create_training_data.py waifu2x --dataset-dir /data/dataset/waifu2x/ --data-dir ./data/waifu2x_320 --size 320
```
(`--dataset-dir` should be changed to the correct directory path)
then use `--data-dir ./data/waifu2x_320` for `train.py`

**Comment by My12123** [comment]
(nunif) F:\nunif>python train.py waifu2x --method scale --arch waifu2x.upcunet --data-dir ./data/waifu2x --model-dir ./models/waifu2x_mymodel --num-workers 8 --batch-size 32 --resume
{'adam_beta1': 0.9,
 'amp_float': 'fp16',
 'arch': 'waifu2x.upcunet',
 'b4b': False,
 'backward_step': 1,
 'batch_size': 32,
 'checkpoint_file': None,
 'da_chshuf_p': 0.0,
 'da_color_p': 0.0,
 'da_grayscale_p': 0.0,
 'da_jpeg_p': 0.0,
 'da_scale_p': 0.25,
 'da_unsharpmask_p': 0.0,
 'data_dir': './data/waifu2x',
 'deblur': 0.0,
 'disable_amp': False,
 'disable_backup': False,
 'discriminator': None,
 'discriminator_learning_rate': None,
 'discriminator_only': False,
 'discriminator_stop_criteria': 0.5,
 'discriminator_weight': 1.0,
 'freeze': False,
 'generator_start_criteria': 0.9,
 'gpu': [0],
 'handler': <function train at 0x000001DFE0E95AB0>,
 'hard_example': 'linear',
 'hard_example_scale': 4.0,
 'learning_rate': 0.0002,
 'learning_rate_cycles': 5,
 'learning_rate_decay': 0.995,
 'learning_rate_decay_step': [1],
 'loss': None,
 'max_epoch': 200,
 'method': 'scale',
 'model_dir': './models/waifu2x_mymodel',
 'momentum': 0.9,
 'noise_level': None,
 'num_samples': 50000,
 'num_workers': 8,
 'optimizer': 'adamw',
 'prefetch_factor': 4,
 'reset_state': False,
 'resize_blur_p': 0.1,
 'resume': True,
 'scheduler': 'cosine',
 'seed': 71,
 'size': 112,
 'style': 'art',
 'update_criterion': 'psnr',
 'warmup_epoch': 0,
 'warmup_learning_rate': 1e-06,
 'weight_decay': 0.001}
Traceback (most recent call last):
  File "F:\nunif\train.py", line 22, in <module>
    main()
  File "F:\nunif\train.py", line 18, in main
    args.handler(args)
  File "F:\nunif\waifu2x\training\train.py", line 37, in train
    trainer.fit()
  File "F:\nunif\nunif\training\trainer.py", line 109, in fit
    self.initialize()
  File "F:\nunif\nunif\training\trainer.py", line 41, in initialize
    self.train_loader = self.create_dataloader(type="train")
  File "F:\nunif\waifu2x\training\trainer.py", line 407, in create_dataloader
    dataset = Waifu2xDataset(
  File "F:\nunif\waifu2x\training\dataset.py", line 183, in __init__
    super().__init__(input_dir, num_samples=num_samples)
  File "F:\nunif\waifu2x\training\dataset.py", line 146, in __init__
    raise RuntimeError(f"{input_dir} is empty")
RuntimeError: ./data/waifu2x\train is empty

**Comment by My12123** [comment]
(nunif) F:\nunif>python train.py waifu2x --method scale --arch waifu2x.upcunet --data-dir ./data/waifu2x --model-dir ./models/waifu2x_mymodel --num-workers 8 --batch-size 32 --resume
{'adam_beta1': 0.9,
 'amp_float': 'fp16',
 'arch': 'waifu2x.upcunet',
 'b4b': False,
 'backward_step': 1,
 'batch_size': 32,
 'checkpoint_file': None,
 'da_chshuf_p': 0.0,
 'da_color_p': 0.0,
 'da_grayscale_p': 0.0,
 'da_jpeg_p': 0.0,
 'da_scale_p': 0.25,
 'da_unsharpmask_p': 0.0,
 'data_dir': './data/waifu2x',
 'deblur': 0.0,
 'disable_amp': False,
 'disable_backup': False,
 'discriminator': None,
 'discriminator_learning_rate': None,
 'discriminator_only': False,
 'discriminator_stop_criteria': 0.5,
 'discriminator_weight': 1.0,
 'freeze': False,
 'generator_start_criteria': 0.9,
 'gpu': [0],
 'handler': <function train at 0x000001DFE0E95AB0>,
 'hard_example': 'linear',
 'hard_example_scale': 4.0,
 'learning_rate': 0.0002,
 'learning_rate_cycles': 5,
 'learning_rate_decay': 0.995,
 'learning_rate_decay_step': [1],
 'loss': None,
 'max_epoch': 200,
 'method': 'scale',
 'model_dir': './models/waifu2x_mymodel',
 'momentum': 0.9,
 'noise_level': None,
 'num_samples': 50000,
 'num_workers': 8,
 'optimizer': 'adamw',
 'prefetch_factor': 4,
 'reset_state': False,
 'resize_blur_p': 0.1,
 'resume': True,
 'scheduler': 'cosine',
 'seed': 71,
 'size': 112,
 'style': 'art',
 'update_criterion': 'psnr',
 'warmup_epoch': 0,
 'warmup_learning_rate': 1e-06,
 'weight_decay': 0.001}
Traceback (most recent call last):
  File "F:\nunif\train.py", line 22, in <module>
    main()
  File "F:\nunif\train.py", line 18, in main
    args.handler(args)
  File "F:\nunif\waifu2x\training\train.py", line 37, in train
    trainer.fit()
  File "F:\nunif\nunif\training\trainer.py", line 109, in fit
    self.initialize()
  File "F:\nunif\nunif\training\trainer.py", line 41, in initialize
    self.train_loader = self.create_dataloader(type="train")
  File "F:\nunif\waifu2x\training\trainer.py", line 407, in create_dataloader
    dataset = Waifu2xDataset(
  File "F:\nunif\waifu2x\training\dataset.py", line 183, in __init__
    super().__init__(input_dir, num_samples=num_samples)
  File "F:\nunif\waifu2x\training\dataset.py", line 146, in __init__
    raise RuntimeError(f"{input_dir} is empty")
RuntimeError: ./data/waifu2x\train is empty

(nunif) F:\nunif>python train.py waifu2x --method scale --arch waifu2x.upcunet --data-dir F:\nunif\waifu2x --model-dir ./models/waifu2x_mymodel --num-workers 8 --batch-size 32 --resume
{'adam_beta1': 0.9,
 'amp_float': 'fp16',
 'arch': 'waifu2x.upcunet',
 'b4b': False,
 'backward_step': 1,
 'batch_size': 32,
 'checkpoint_file': None,
 'da_chshuf_p': 0.0,
 'da_color_p': 0.0,
 'da_grayscale_p': 0.0,
 'da_jpeg_p': 0.0,
 'da_scale_p': 0.25,
 'da_unsharpmask_p': 0.0,
 'data_dir': 'F:\\nunif\\waifu2x',
 'deblur': 0.0,
 'disable_amp': False,
 'disable_backup': False,
 'discriminator': None,
 'discriminator_learning_rate': None,
 'discriminator_only': False,
 'discriminator_stop_criteria': 0.5,
 'discriminator_weight': 1.0,
 'freeze': False,
 'generator_start_criteria': 0.9,
 'gpu': [0],
 'handler': <function train at 0x000001D231125AB0>,
 'hard_example': 'linear',
 'hard_example_scale': 4.0,
 'learning_rate': 0.0002,
 'learning_rate_cycles': 5,
 'learning_rate_decay': 0.995,
 'learning_rate_decay_step': [1],
 'loss': None,
 'max_epoch': 200,
 'method': 'scale',
 'model_dir': './models/waifu2x_mymodel',
 'momentum': 0.9,
 'noise_level': None,
 'num_samples': 50000,
 'num_workers': 8,
 'optimizer': 'adamw',
 'prefetch_factor': 4,
 'reset_state': False,
 'resize_blur_p': 0.1,
 'resume': True,
 'scheduler': 'cosine',
 'seed': 71,
 'size': 112,
 'style': 'art',
 'update_criterion': 'psnr',
 'warmup_epoch': 0,
 'warmup_learning_rate': 1e-06,
 'weight_decay': 0.001}
F:\2\envs\nunif\lib\site-packages\torch\utils\data\dataloader.py:554: UserWarning: This DataLoader will create 8 worker processes in total. Our suggested max number of worker in current system is 4 (`cpuset` is not taken into account), which is smaller than what this DataLoader is going to create. Please be aware that excessive worker creation might get DataLoader running slow or even freeze, lower the worker number to avoid potential slowness/freeze if necessary.
  warnings.warn(_create_warning_msg(
scheduler=cosine: max_epoch: 200 -> 199
* load checkpoint from ./models/waifu2x_mymodel\scale2x.checkpoint.pth
----------------------------------------------------------------
 epoch: 7, lr: [[0.000189, 0.000189]]
--
 train
  0%|                                                  | 0/1562 [00:00<?, ?it/s]
The training didn't start, it took off.

**Comment by My12123** [comment]
(nunif) F:\nunif>python train.py waifu2x --method noise_scale --arch waifu2x.upcunet --data-dir F:\nunif\waifu2x --model-dir ./models/waifu2x_mymodel --num-workers 4
{'adam_beta1': 0.9,
 'amp_float': 'fp16',
 'arch': 'waifu2x.upcunet',
 'b4b': False,
 'backward_step': 1,
 'batch_size': 16,
 'checkpoint_file': None,
 'da_chshuf_p': 0.0,
 'da_color_p': 0.0,
 'da_grayscale_p': 0.0,
 'da_jpeg_p': 0.0,
 'da_scale_p': 0.25,
 'da_unsharpmask_p': 0.0,
 'data_dir': 'F:\\nunif\\waifu2x',
 'deblur': 0.0,
 'disable_amp': False,
 'disable_backup': False,
 'discriminator': None,
 'discriminator_learning_rate': None,
 'discriminator_only': False,
 'discriminator_stop_criteria': 0.5,
 'discriminator_weight': 1.0,
 'freeze': False,
 'generator_start_criteria': 0.9,
 'gpu': [0],
 'handler': <function train at 0x000001F15DA75AB0>,
 'hard_example': 'linear',
 'hard_example_scale': 4.0,
 'learning_rate': 0.0002,
 'learning_rate_cycles': 5,
 'learning_rate_decay': 0.995,
 'learning_rate_decay_step': [1],
 'loss': None,
 'max_epoch': 200,
 'method': 'noise_scale',
 'model_dir': './models/waifu2x_mymodel',
 'momentum': 0.9,
 'noise_level': None,
 'num_samples': 50000,
 'num_workers': 4,
 'optimizer': 'adamw',
 'prefetch_factor': 4,
 'reset_state': False,
 'resize_blur_p': 0.1,
 'resume': False,
 'scheduler': 'cosine',
 'seed': 71,
 'size': 112,
 'style': 'art',
 'update_criterion': 'psnr',
 'warmup_epoch': 0,
 'warmup_learning_rate': 1e-06,
 'weight_decay': 0.001}
Traceback (most recent call last):
  File "F:\nunif\train.py", line 22, in <module>
    main()
  File "F:\nunif\train.py", line 18, in main
    args.handler(args)
  File "F:\nunif\waifu2x\training\train.py", line 16, in train
    raise ValueError("--noise-level is required for noise/noise_scale")
ValueError: --noise-level is required for noise/noise_scale

**Comment by My12123** [comment]
How to fix it?

**Comment by nagadomi** [comment]
>The training didn't start, it took off.

I don't know your system's directory structure.
It is a bit confusing, nunif's training workflow has two data directories: `--dataset-dir` and `--data-dir`.

`--dataset-dir`:  source directory for `--data-dir`. high-resolution images are stored. not used in `train.py`.
`--data-dir`: This contains images from `--dataset-dir` split into 640x640 (default) or 320x320 (--size 320). it is created by `create_training_data.py`. specify this for `train.py`.

Are all images under `F:\nunif\waifu2x` 320x320? 

----
>--method noise_scale

When `--method noise_scale` is specified, `--noise-level <0-3>` must be specified.
It means low(0), middle(1),high(2),highest(3) on the web UI.
```
--method noise_scale --noise-level 0
```

**Comment by My12123** [comment]
61 images are used for training at 640 it turns out 1538 at 320 more than 10000

**Comment by nagadomi** [comment]
>What is Batch Y-PSNR: 37.0081?

It is a simple evaluation metrics for reconstruction quality. Y means it is calculated in luminance space (Y of YUV).
The higher the value, the better the quality. See https://en.wikipedia.org/wiki/Peak_signal-to-noise_ratio

Note that Y-PSNR value displayed in the training is affected by settings such as --batch-size, so to evaluate it correctly, use waifu2x.benchmark.

> 320 more than 10000

Does this still error (get stuck)?

**Comment by My12123** [comment]
Yes, it does not work for a long time, it loads, and then crashes.

**Comment by My12123** [comment]
I managed to increase the speed of learning and GPU usage.
![2023-04-07_12-44-13](https://user-images.githubusercontent.com/49092250/230586854-118dd3c8-2da5-4a9e-9771-13ec9ca32c44.png)

**Comment by nagadomi** [comment]
What was the problem in the end?
I suspected that you were getting an out-of-memory error by specifying the original resolution directory for `--data-dir`.

---
Also, if the disk io is not a bottleneck, you can make it faster by specifying `--size 88` option (use 88x88 patch for training input instead of 112x112). This will slightly affect model accuracy, but I don't think it has a big negative impact.
(`--size 64` will be much faster, but I am not sure how much it will degrade or not, for cunet models.)

**Comment by My12123** [comment]
It is possible to use HDD and in `--batch-size 32`

**Comment by nagadomi** [comment]
If `--batch-size` was the problem, it may be GPU side out-of-memory error(VRAM).
When `--size` or `--batch-size` is large, more GPU memory is used.
In older versions of Windows, CUDA errors sometimes caused the system to freeze, so this may still happen.
