### ISSUE TITLE
recent update reduced speed by 10x

### ISSUE THREAD

**Issue by longbottom-neville** [nagadomi/nunif#213]
So with any v2 S, i used to get 8-10 fps, however its 0.5fps after I updated it today, Is there any way I can revert the update, please?

**Comment by andy500** [comment]
your recent update crash my computer l am using the backup with out the update working ok back to the speed l was getting

**Comment by longbottom-neville** [comment]
how are you using the backup without the update @andy500? please!

**Comment by nagadomi** [comment]
I made an option whether to use CUDA streams added in the recent update. It is off by default.

![cuda_stream_option](https://github.com/user-attachments/assets/ffec9a61-3148-41c9-a893-2ebc8f0cf6e9)

Run `update.bat` and try again.

**Comment by nagadomi** [comment]
Make sure that the problem occurs only when the `Stream` option is checked.

**Comment by nagadomi** [comment]
In my env(RTX3070ti Linux), 1080p input, Any_V2_S, Depth Batch Size=8, Worker Threads=2,

Stream OFF: 48FPS
Stream ON: 61FPS

**Comment by longbottom-neville** [comment]
Interesting, so with cuda streams on my speed is 10x slow however with it off its the same speed that I used to get before but this is with 4k videos, in 1080p however the speed remains same irrelevant to cuda streams off or on. 
Funny thing is my system is almost similar to yours yet very different speeds, how are you getting 40+ omg

my system - 
windows 11
R9 5900HX
RTX 3080
32GB RAM
3TB Nvme

my speed way less than yours, I'm not sure how

So with 4k video in Any V2 S :
CUDA stream off - 3.5fps
CUDA stream on - 0.5fps

In 1080p videos in Any V2 S:
CUDA stream off - 24 fps
CUDA stram on - 24fps

**Comment by longbottom-neville** [comment]
![Screenshot 2024-09-01 111257](https://github.com/user-attachments/assets/5cd167cc-d573-40cb-b6a8-3cd1c6a8091f)

**Comment by nagadomi** [comment]
When Stream ON, VRAM usage had increased 2-3 GB in my env.
The performance problem seems to occur at higher resolutions, so it is possible that VRAM is swapping (I'm not too familiar with this, but Windows GPU driver have Virtual VRAM feature).
Batch Size=4 or 2 might help.

**Comment by longbottom-neville** [comment]
I see, without Stream On my vram already around 7.8GB out of mine 8GB gpu, so I guess I wont get much with Stream On?

Also would you say I'd get 30-40% more frames  from linux system just like yours?

Thanks again

**Comment by longbottom-neville** [comment]
![Uploading Screenshot 2024-09-01 135447.png…]()

**Comment by longbottom-neville** [comment]
![Screenshot 2024-09-01 135447](https://github.com/user-attachments/assets/bf0be744-61f8-46e1-95c7-0d2e33ba5403)

**Comment by nagadomi** [comment]
VRAM usage can be reduced by decreasing Depth Batch Size.
When VRAM is full, Windows GPU driver may use very slow memory transfers (it's `Shared GPU Memory` in that screenshot).

>Also would you say I'd get 30-40% more frames from linux system just like yours?

Probably.
PyTorch is slow on Windows. But I have not researched it in detail. There are many causes for it.

**Comment by longbottom-neville** [comment]
since the task was 30% done when you suggested to decrease the batch size, I'll wait for it to finish and then try a new task with lower batch size, thanks for your help and for your amazing work with iw3

**Comment by longbottom-neville** [comment]
Hey nagadomi, I've a small query, thought I'd just ask here instead of burdening you with a new thread, with certain mkv files i get this error:

"Application provided invalid, non monotonically increasing dts to muxer in stream 1:2033>=2005"

This only happens with certain files and the task fails, any idea would be greatly appreciated.

Also, can you please share ur paypal id, you've been of great help I want to get you a beer atleast for all you've done for us :)

**Comment by diverswan9** [comment]
@longbottom-neville  I've had that before. I think it may have do with the audio track. I'll run just the video track usually... less problems.

**Comment by kaelsonofkrypto** [comment]
> I made an option whether to use CUDA streams added in the recent update. It is off by default.
> 
> ![cuda_stream_option](https://private-user-images.githubusercontent.com/287255/363453024-ffec9a61-3148-41c9-a893-2ebc8f0cf6e9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUyMzM4MTAsIm5iZiI6MTcyNTIzMzUxMCwicGF0aCI6Ii8yODcyNTUvMzYzNDUzMDI0LWZmZWM5YTYxLTMxNDgtNDFjOS1hODkzLTJlYmM4ZjBjZjZlOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTAxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkwMVQyMzMxNTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jZGE3YWY3NjdjYTdlMjg1OTVkNWQ4OGM3ODY4MjIzMTFhNTkwNmY4ZjM4NTE0ZjNjOGNjZjQwYTYwY2MxYTlkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.FZea_zSnt44QyXASFnFoObnO6ADMu2wbizzO9ppHZ4A)
> 
> Run `update.bat` and try again.

what is the purpose of the Streams, what does it exactly do?

**Comment by nagadomi** [comment]
@longbottom-neville 
>"Application provided invalid, non monotonically increasing dts to muxer in stream 1:2033>=2005"

`stream 1` is audo track, as diverswan9 says (stream 0: video track, stream 1: audio track in iw3).
Could you try specifying `Start Time=00:00:01`(checked) and getting the same error?
(When `Start Time` is specified, auto track will be re-encoding)

>Also, can you please share ur paypal id

This project has Patreon link. https://patreon.com/nagadomi

**Comment by nagadomi** [comment]
@kaelsonofkrypto
When `Worker Threads` is non-zero, each batch is processed by multi threads, but using the same CUDA Stream (GPU processing pipeline).
When `Stream` is checked, different CUDA Stream is used for each thread. This can actually parallelize CUDA processing pipeline.
(I used this feature first time, so I'm not too sure if it is right.)

**Comment by nagadomi** [comment]
@andy500 from #218
>so l try your new update and fix update on my 2070 rtx 20min clip with stream off 24 hours with stream on 1 hour 50min about but l use my
>one that l backup before update with no stream in the program and it took 60min much faster you have a bug in your update


I tried to compare with 8bef536310955800a4f475755e9cbbb3a0194378 before the change but could not reproduce it.

Here's what I suspect is the problem with the setting you were posting to https://github.com/nagadomi/nunif/discussions/212

>TTA=ON

You have TTA turned on only on the 2070 side.
TTA makes the processing time twice as long. Make sure you are using the same settings.

>Any_V2_B Depth Batch Size=16, Worker Thread=8

2070 has 8GB VRAM. I think this setting value is too large. It may cause [VRAM swapping](https://www.reddit.com/r/StableDiffusion/comments/x308i4/comment/immq838/) on Windows.
I think `Batch Size=8, Worker Thread=2` or `Batch Size=2, Worker Thread=8` is safe.

> Stereo Processing Width=1280 or 1920

`Stereo Processing Width` is not recommended for normal video conversion.
It is slower than `Default` and less affective.

**Comment by andy500** [comment]
thank you will try the settings see how it goes when should l use Stereo Processing Width
