### ISSUE TITLE
NEW UPDATE SLOW CONVERSION SPEED

### ISSUE THREAD

**Issue by andy500** [nagadomi/nunif#218]
so l try your new update and fix update on my 2070 rtx 20min clip with stream off 24 hours  with stream on 1 hour 50min about but l use my 
one that  l backup before update  with no stream in the program  and it took 60min much faster you have a bug in your update

**Comment by nagadomi** [comment]
I replied to https://github.com/nagadomi/nunif/issues/213#issuecomment-2325695373

close as duplicate issue
