### ISSUE TITLE
Drag & drop folders may cause folder deletion in Windows 11

### ISSUE THREAD

**Issue by kice** [nagadomi/nunif#231]
For example if I have folder C:\1\2, and open this path in File Explorer, then drag from the address bar to iw3.gui (the red box in the screenshot below), the folder will be deleted (iw3 is able the receive the dropped path and set the input box).

![image](https://github.com/user-attachments/assets/2916e662-f407-4fdb-b5a7-a83f0d59bfc5)

I also noticed the behavior of other application treat this kind of action as COPY, while iw3 treats it as MOVE. This might be the cause?

**Comment by nagadomi** [comment]
iw3 does not execute any operations to D&D files/folders.
So I guess that MOVE or DELETE operations are executed by Explorer.
On Windows 10, D&D folder did not get moved or deleted.

>I also noticed the behavior of other application treat this kind of action as COPY, while iw3 treats it as MOVE. This might be the cause?

I do not have Windows 11, but can confirm this behavior on Windows 10.
For now, I will find a way to change this to “COPY”.
It is maybe related to [wx.DragResult](https://docs.wxpython.org/wx.DragResult.enumeration.html).

**Comment by nagadomi** [comment]
I changed the default action to wx.DragCopy. https://github.com/nagadomi/nunif/commit/503a2d59377bc921855ce5256b6da6f7f665d8d3
Would you try again on Windows 11 after running `update.bat`?

**Comment by kaelsonofkrypto** [comment]
im so confused about this issue what was the fix for exactly, sorry, are you all saying you can drag folders in iw3 , i always just pressed the folder button for it to bulk convert, im so confused

**Comment by kice** [comment]
@kaelsonofkrypto drag & drop feature was added last year. But you can only drag & drop one file or one folder at a time. 

This issue tries to fix a bug with this feature.

**Comment by kice** [comment]
@nagadomi I tested on win11, and it was fixed. The DnD action is COPY now, and my folder does not get deleted.

If there is not other things to test, I think you could close the issue.

~~RIP my files~~

**Comment by kaelsonofkrypto** [comment]
> @kaelsonofkrypto drag & drop feature was added last year. But you can only drag & drop one file or one folder at a time.
> 
> This issue tries to fix a bug with this feature.

how do you do that, on the iw3 i have i don't see an area where to drag and drop?
![image](https://github.com/user-attachments/assets/ce37d3a5-6ea4-4019-ab48-738a0fb3da5d)

**Comment by kice** [comment]
@kaelsonofkrypto 
Drop it to anywhere in the application window should work.

If not working, then try to update the application or download the latest version.

**Comment by nagadomi** [comment]
Thanks for testing. I will close this issue.

>RIP my files

:cry:
I am not very familiar with Windows, but I suspect this is a bug in Explorer.
My common sense tells me that file manipulation should be handled by the receiver side(iw3). To me it seems a strange behavior that the sender side(Explorer) (or both) manipulates the file.
But I apologize if it was my mistake.

**Comment by kaelsonofkrypto** [comment]
> @kaelsonofkrypto Drop it to anywhere in the application window should work.
> 
> If not working, then try to update the application or download the latest version.

thanks ill try it
