### ISSUE TITLE
Consider integrating DepthCrafter for video depth estimation

### ISSUE THREAD

**Issue by Haor** [nagadomi/nunif#233]
DepthCrafter (https://github.com/Tencent/DepthCrafter) is a newly released open-source project for video depth estimation. It claims to offer better temporal consistency and fine-grained details compared to methods like Depth-Anything v2, especially for long video sequences.

Could you consider evaluating DepthCrafter and potentially integrating it as an optional depth estimation method in iw3? This could provide users with more choices for different video processing needs.

Key potential benefits:
- Improved temporal consistency
- Better handling of open-world videos
- Options for both high and low resolution inference

Thank you for considering this suggestion.

**Comment by nagadomi** [comment]
See https://github.com/nagadomi/nunif/discussions/226#discussioncomment-10648587
