### ISSUE TITLE
Getting slight "over-draw" with resized images (probably only small images)

### ISSUE THREAD

**Issue by shuttittuppitt** [nagadomi/nunif#242]
![005](https://github.com/user-attachments/assets/6f057413-4f8a-4deb-88ab-5a402bedc27e)

I just now noticed (probably because I haven't used it for awhile) that some images experience what looks _similar_ (but not identical) to a slight "over-draw" along the bottom row. By that, I mean that it looks _similar_ to having the bottom row of an image duplicated into the 2 bottom rows of the result. (An image editor that I use shows that the resulting bottom lines are _not_ identical, only similar.)

(I use this site to use waifu = https://unlimited.waifu2x.net/)
Mostly I use "swin_unet / photo". When I noticed this strange effect, I tried the following to see what is causing it.
* I changed the DeNoise setting.
* I turned TTA both on & off.
* I used a version of the image that is rotated 180 degrees.
None of those things fixed the problem. The rotated image showed the result along _it's new_ bottom row instead, so the _content_ of an image's bottom row doesn't seem to be what causes it.

I assume that the small dimensions of the images that experience the effect are causing waifu to do this. Even if it does affect large images too, their size would make the result almost unnoticeable if they are affected.

**Comment by nagadomi** [comment]
It is perhaps artifact(noise) of replication padding.
waifu2x pads the input image to a multiple of the tile size, then upscaled and cropped the valid area of the result.
I changed the padding algorithm `reflect` to `replicate` on 2024-7-21 because of #183 bug.

reflect
![reflect_pad](https://github.com/user-attachments/assets/f7d14b65-5bd6-4e5a-a93a-dddd9614e56a)
replicate
![replicate_pad](https://github.com/user-attachments/assets/9764e1b2-a410-47ce-ab67-8b288db8a524)


I plan to revert to using reflection padding, which fixed #183 bug.

**Comment by nagadomi** [comment]
Changed to use modified version of reflection padding (unlimited.waifu2x.net only).
From my visual inspection, the problem has been fixed.
If the result is the same, try clearing your browser cache.

**Comment by nagadomi** [comment]
Sorry, I have rolled back the changes above.
I suspect this is a bug of a different cause than I expected.

**Comment by nagadomi** [comment]
test image
![dot2](https://github.com/user-attachments/assets/a1ec1d85-5251-488a-a412-c01795f85590)

When this image is upscaled to 4x using swin_unet/art, the white line on top and the black line on the bottom are exactly 4px.
So there is no bug in the image processing.
However, given a typical art image, the results are obviously affected by padding pixels.
It is possible that the model is learned corner alignment of resample filters (If the input looks like bicubic downsampling or bilinear downsampling).

**Comment by nagadomi** [comment]
Changed to use reflection padding for photo model and replication padding for art model.
If the result is the same, try clearing your browser cache.
