### ISSUE TITLE
What is your Butch Y-PSNR indicator in pretrained_models and onnx_models?

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#25]
What is your Butch Y-PSNR indicator in pretrained_models and onnx_models?
I now have Batch Y-PSNR: 37.4759

**Comment by nagadomi** [comment]
It  depends on the image data used for evaluation.
You can use `waifu2x.benchmark` command to evaluate the trained model.

examples:
`-m`: mehtod (scale, noise_scale, scale4x noise_scale4x)
`--model-dir`: Specify the model directory.
`-i`: Specify the image directory to be used for evaluation.


pretrained cunet/art model
```
python -m waifu2x.benchmark -m scale --model-dir waifu2x/pretrained_models/cunet/art -i /path_to_image_folder
```
pretrained swin_unet/art model (2x)
```
python -m waifu2x.benchmark -m scale --model-dir waifu2x/pretrained_models/swin_unet/art -i /path_to_image_folder
```

your trained model
```
python -m waifu2x.benchmark -m scale --model-dir F:\nunif\models\waifu2x_mymodel -i /path_to_image_folder
```


The onnx models simply have different file formats. same parameters.
