### ISSUE TITLE
Feature Request: Selecting Depth Model and Settings Scene by Scene with Preview: Edit feature

### ISSUE THREAD

**Issue by Archit01** [nagadomi/nunif#252]
Feature Request: Selecting Depth Model and Settings Scene by Scene with Preview: Edit feature

Hello,

I would kindly request you to add the following feature if possible and as per your convivence i.e. 
1.) Preview based editing mode with timeline where we could assign a specific depth model and convergence and divergence and other settings scene by scene basis like in a long video from 1 min to 2min this setting and then another etc. This will give us the complete freedom to convert 2D to 3d in one software rather than edit it in multiple software's and also this will make the workflow much faster and better. 
2.) Additionally, if there will be Realtime/preprocess preview it can help to adjust the settings much more efficiently scene by scene basis.

Thank you

**Comment by nagadomi** [comment]
I have no intention of developing big video editing software. 
VR video player that can adjust Depth/SBS parameters in real time may be developed if there is still demand for it in a few years.
