### ISSUE TITLE
Tune settings seem messed up with fastdecode option.

### ISSUE THREAD

**Issue by beosliege** [nagadomi/nunif#253]
It seems that the 'Tune' dropdown menu items are messed up with the fastdecode and zerolatency check box options in the latest version of iw3.

'Still Image' has disappeared from the Tune menu as an option.
fastdecode and zerolatency are appearing on the Tune menu and the check boxes for these are disabled.

![image](https://github.com/user-attachments/assets/982855cc-9bdb-458f-b361-cce0d9339d96)

![image](https://github.com/user-attachments/assets/3a5f57b5-0001-4607-a861-5135054e85e2)

**Comment by beosliege** [comment]
Update: This occurs when selecting libx265. If selecting libx264, then the Tune menu and the check boxes for fastdecode and zerolatency work as expected.

**Comment by beosliege** [comment]
Thank you for the explanation! And I apologize for the oversight on my end. I should have looked at this closer before starting this issue.

Confirmed that when using libx264 I can specify multiple tune settings:
ffmpeg -i Output_000.mp4 -c:v libx264 -tune stillimage,fastdecode output_video.mp4
This is why the check boxes in iw3 make sense to have for fastdecode and zerolatency alongside the drop-down for a third option.

Confirmed a single option works in libx265:
ffmpeg -i Output_000.mp4 -c:v libx265 -tune grain output_video.mp4

Confirmed more than one option does NOT work in libx265:
ffmpeg -i Output_000.mp4 -c:v libx265 -tune grain,fastdecode output_video.mp4
This is why the check boxes for fastdecode and stillimage are not necessary in iw3 when using x265.

Confirmed the options that are available in iw3 reflect those available by x264 and x265:

ffmpeg -hide_banner -f lavfi -i nullsrc -c:v libx264 -preset help -f mp4 -
Possible tunes: film animation grain stillimage psnr ssim fastdecode zerolatency

ffmpeg -hide_banner -f lavfi -i nullsrc -c:v libx265 -preset help -f mp4 -
Possible tunes: psnr ssim grain zerolatency fastdecode animation

**Comment by nagadomi** [comment]
Yes. libx265 is not just an upgraded version of libx264, it may have different options and behavior for options.
I am not too sure what the difference is, but options that simply result in an error are eliminated.
