### ISSUE TITLE
IW3 png resume attempts to parse thumbs.db and crashes 

### ISSUE THREAD

**Issue by sentrywasbored** [nagadomi/nunif#260]
When resuming an iw3 interpolation operation, the system checks the rgb folder to detect where to pick up from. This check somehow is sweeping up the thumbs.db file autogenerated by windows to house generated thumbnails for Explorer and causes an int() error

**Comment by sentrywasbored** [comment]
issue could likely be patched if a check was implemented to verify that the extension on latest_checkpoint_filename matches the user-set Image Format.

**Comment by nagadomi** [comment]
Fixed https://github.com/nagadomi/nunif/commit/c221ab0509905c46ef377779e58f2579f8e55563
I haven't actually tested it on Windows, but it should be fixed.
