### ISSUE TITLE
[ENHANCEMENT] SWAP EYES

### ISSUE THREAD

**Issue by shinra358** [nagadomi/nunif#261]
can we get eye swap settings L/R and R/L under Stereo Generation section pls, thanks. It will allow to make cross eyed images to quickly test so we wont have to deal with the lag in constantly switching tvs between 2d and 3d modes.

**Comment by nagadomi** [comment]
I can add that feature, but I don't think it is very practical.
This is because on VR video player, the 3D visual effect depends on the screen size and distance, so checking in other ways is not very helpful.

In my case, I use Anaglyph for quick checks for debugging.
Red Cyan Anaglyph 3D glasses are available on Amazon for $5.
However, it only confirms whether it is completely broken or possibly normal.

**Comment by shinra358** [comment]
this would be a process that happens after the conversion is done to the finished image only. this is so one can use cross eyes if they dont feel like turning on 3D atm. For my 3Dtv setup, using swap will allow to view with 3D glasses and cross eyes. A 2 in 1. Then on my tv, i can change it's settings to swap so the depth would be inverse. I vr headset would have this option too. But having swap here would have a 2 in 1 at the ready and reduces the continuous switching on the actual device when editing or testing :)

**Comment by nagadomi** [comment]
For videos that have already finished 3D (SBS) conversion,
you can use ffmpeg to swap the left and right sides of the video.
```
ffmpeg -i input_video.mp4 -filter_complex "[0:v]crop=iw/2:ih:0:0[left]; [0:v]crop=iw/2:ih:iw/2:0[right]; [right][left]hstack" -c:v libx264 -crf 20  lr_swap.mp4
```
This should be much faster than 3D conversion twice.

**Comment by shinra358** [comment]
is that the cmdline version or is that the version to copy and paste in the -vf section? If it's the latter, what's the version that goes in the -vf section?

**Comment by nagadomi** [comment]
closed.
This is not a commonly used feature and can be achieved more efficiently in other ways.

**Comment by shinra358** [comment]
It actually is common. It's a staple option in every program that shows 3D. Every emulator that has 3D options has it, Owl3D has it (called cross eye mode), my TV has it, Nvidia 3D vision had it, tridef, iz3d, geo-11, etc all have it. hmd and vr headsets all have it. But thanks for listening. Great program and I enjoy it very much! Very revolutionary.

**Comment by nagadomi** [comment]
If TV or video player has that feature, we can L/R swap during playback. So there is no need to output L/R swap.
I do not believe anyone uses this software for cross-eyed viewing.

**Comment by shinra358** [comment]
as I explained above, it's mostly for testing and quick forum viewing. this
is how ppl who make 3D mods for games display their work and 3D fixes:
https://helixmod.blogspot.com/
as you can see, for over 10 years, we've been using crosseye. Nvidia
themselves use to display like this on their real forums when they were
doing 3D.

**Comment by nagadomi** [comment]
I have added this feature to the dev branch so it will be available some time soon.
https://github.com/nagadomi/nunif/commit/93331b65fd47a6ebdf1f62f3eef7867f6bd45eaa
