### ISSUE TITLE
[QUESTION] Light Rays / Light Effects

### ISSUE THREAD

**Issue by shinra358** [nagadomi/nunif#262]
Is there any way in the future to code the AI to detect light rays or light effects? Currently they are ignored in depth maps and are usually painted on the back far rear plane like grafitti on a wall. Is it because they lack shadows and AI can't detect it as an object to give depth to?

**Comment by nagadomi** [comment]
That is a case where the depth estimation model does not work well.
Subtitles and credit roll text can also look strange. As for text, it can be segmented, so it is possible to move them to the most front. However, there is a risk of false detection.
It would be more challenging for volume, such as light beam and particles (rain, smoke, etc).

Either way, iw3 is currently just using the existing depth estimation models, so it is not possible to support it.
