### ISSUE TITLE
[ENHANCEMENT] Max FPS [Same as Source] Option

### ISSUE THREAD

**Issue by shinra358** [nagadomi/nunif#263]
would like to have Same as Source option for Max FPS setting because I use AI Frame Gen external program for boosting fps. This way, the file size stays smaller.

**Comment by nagadomi** [comment]
Max FPS is the option that sets FPS **limit** for the output video.
If the source video FPS is lower than Max FPS, it will be output using the original source FPS.
So, if you set `Max FPS=1000`, the FPS of the output video will always be the same as the source video.

**Comment by shinra358** [comment]
oh ok
