### ISSUE TITLE
[Visual Enhancement]Foreground/Background Depth Map Object Blur

### ISSUE THREAD

**Issue by shinra358** [nagadomi/nunif#264]
I would like to ask  of some option indicated in the picture to provide blur in the frontmost object and on the backmost plane decided by the color on the depthmap, then it would be transferred to the corresponding image on said depthmap RGB color with a gradient range. Kinda like DOF. Starting color box will be a user configurable R,G,B. No number would be different so only 1 number can be indicated if need be and it will represent the Red, Green, Blue automatically. Blur type would include drop down box of different types of blurs like gaussian or bokeh. A blur strength option (one for the fg and one for the bg), not indicated in pic, would of course dictate how hard or soft the blurs are on the final image and be allocated to the color strengths on the depth map gradient. The closer to the focus, the lighter the blur becomes. The further from the focus, the heavier the blur would become indicated by the blur strength option selection. so if a user inputs 25, no blur will be a 25 depth color but in between 25 and 0, blur will get stronger between the range of 25 and 0 (or 230 to 255 if user inputs 230 for the back):

![DoF idea](https://github.com/user-attachments/assets/903041cb-376e-43cb-815e-0204284c2e26)

Then our images/videos can look like this to mask the double vision on the plane that Foreground Scale can cause if it isn't 0:

![triangle_strategy](https://github.com/user-attachments/assets/198cbbfe-45eb-4628-93d6-a8cc87e4b4b1)

**Comment by nagadomi** [comment]
Where the camera focus is depends on the scene.
I have no motivation to add the ability to edit video/image content subjectively in iw3.

I also think that the blur in the 2D image and the blur on the 3D are not the same thing.
If you focus your viewpoint on the center it should be possible to achieve that.
In VR video player, screen edge distortion is less noticeable when using curved screen.

**Comment by nagadomi** [comment]
I don't remember clearly, but I think there was a technique to fix the problem of double vision at the edges of the screen by turning the left and right cameras inward, so that the left right images are aligned at the edges of the screen.

**Comment by shinra358** [comment]
setting the ip offset to 1 or 2 depending on the image can remedy the issue for the middle and far planes once adjusting the tv focal point to the far right. however the frontmost plane will always have the dual vision nomatter what because that's how real vision works without the glasses. This dof type method will help take ones mind off of it so that the eye wont keep getting magnetized to it.

![negative-foreground-scale](https://github.com/user-attachments/assets/6e77f3a5-7673-4a96-a2ca-8d473f8cc5f0)

If you look at the first image of the dog, the grass in front of the dog is a 255,255,255 solid white. The dog's white is not the same rgb of white. It's something like 200,200,200. so if you target the solid white with the blur, the blur will not affect the other whites. That is how you can get the blur to perfectly replicate on the image just like a 3D image.

And the black bg is 0,0,0 - a solid black. So if you use a blur code to target the rgb of 0,0,0, only that plane in pure black will be affected by blur. And that is how you get the image to look like that of the screen shot of that game.

**Comment by nagadomi** [comment]
In the following example, will the dog get blurry? Do we need to manually adjust all frames?

![dog_font](https://github.com/user-attachments/assets/a038c8ad-d0c2-46dc-8665-005b5f76f1bc)
![dog_font](https://github.com/user-attachments/assets/61a35080-6c7b-4cbd-ba6d-f9f47cda40d9)

----
You can use the export feature to output the depth and use it as blur weight in other image editing software.
Here is an example of editing using GIMP.
![dog_dof1](https://github.com/user-attachments/assets/b51ae1d0-3e76-45c7-af7f-8e05756a5e92)
![dog_dof2](https://github.com/user-attachments/assets/21e442a5-7da7-4015-b1a3-d639291293cb)

Then the edited image can be imported as RGB frame.
For video, similar editing should be possible with DaVinci Resolve, but I have not used it.

**Comment by shinra358** [comment]
![391362184-61a35080-6c7b-4cbd-ba6d-f9f47cda40d9](https://github.com/user-attachments/assets/788d3e0e-f256-4e4b-bd68-d172d481ff12)

the whitest part of the dog here is the nose. but it is not pure white. It's 239,239,239. Pure white is 255,255,255. So if coded in the program the way displayed in initial post:

Front Gradient Blur Inner Start              [245,245,245]
Front Gradient Blur Outward End          [255,255,255] *unconfigurable (locked)

![jj](https://github.com/user-attachments/assets/bb55da70-decb-4ea7-942f-1a48c15dc8c4)

Then the only thing that will be blurred is the front most part of the ground the dog is standing on which are the colors 245 - 255. Since the dog's nose is 239 and the whitest part of the ground below it is 251, it is not in the range to get blurred. So only the colors between this range will be blurred. Photoshop and gimp doesn't have this feature to do it this way.  At least in this simplest way. This would be a brand spanking new evolution.

@14:43 https://www.youtube.com/watch?v=JvJkEg5BT9E - this is similar, but doing this to a video by just buying or downloading 2 other programs is not practical nor fast. And this won't be as accurate as the initiate post. And then those programs are processing them all over again, it just elongates the time of production.
