### ISSUE TITLE
Installation and Upgrade Error

### ISSUE THREAD

**Issue by carlobs** [nagadomi/nunif#265]
I use IW3 since months,
today i launched the update-installer.bat, then update.bat 
but one error occour (WIN 11, Microsoft Visual C++ )

So i deleted the entire folder and reinstalled all (after re downloading the .zip from here), but ever with the same error:
 

![immagine](https://github.com/user-attachments/assets/b4e3274e-6c84-4461-9fc4-722c535fa6bb)

any idea how to solve the problem?

Thank you

`
Already up to date.
Install Python Packages...
Requirement already satisfied: pip in d:\nunif-windows\python\lib\site-packages (24.3.1)
Looking in indexes: https://pypi.org/simple, https://download.pytorch.org/whl/cpu, https://download.pytorch.org/whl/cu124
Ignoring torch: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "darwin"' don't match your environment
Ignoring torch: markers 'sys_platform == "linux"' don't match your environment
Ignoring torchvision: markers 'sys_platform == "linux"' don't match your environment
Requirement already satisfied: torch==2.4.1+cu124 in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements-torch.txt (line 13)) (2.4.1+cu124)
Requirement already satisfied: torchvision==0.19.1+cu124 in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements-torch.txt (line 14)) (0.19.1+cu124)
Requirement already satisfied: filelock in d:\nunif-windows\python\lib\site-packages (from torch==2.4.1+cu124->-r D:\nunif-windows\nunif\requirements-torch.txt (line 13)) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\nunif-windows\python\lib\site-packages (from torch==2.4.1+cu124->-r D:\nunif-windows\nunif\requirements-torch.txt (line 13)) (4.12.2)
Requirement already satisfied: sympy in d:\nunif-windows\python\lib\site-packages (from torch==2.4.1+cu124->-r D:\nunif-windows\nunif\requirements-torch.txt (line 13)) (1.13.3)
Requirement already satisfied: networkx in d:\nunif-windows\python\lib\site-packages (from torch==2.4.1+cu124->-r D:\nunif-windows\nunif\requirements-torch.txt (line 13)) (3.4.2)
Requirement already satisfied: jinja2 in d:\nunif-windows\python\lib\site-packages (from torch==2.4.1+cu124->-r D:\nunif-windows\nunif\requirements-torch.txt (line 13)) (3.1.4)
Requirement already satisfied: fsspec in d:\nunif-windows\python\lib\site-packages (from torch==2.4.1+cu124->-r D:\nunif-windows\nunif\requirements-torch.txt (line 13)) (2024.10.0)
Requirement already satisfied: numpy in d:\nunif-windows\python\lib\site-packages (from torchvision==0.19.1+cu124->-r D:\nunif-windows\nunif\requirements-torch.txt (line 14)) (1.26.4)
Requirement already satisfied: pillow!=8.3.*,>=5.3.0 in d:\nunif-windows\python\lib\site-packages (from torchvision==0.19.1+cu124->-r D:\nunif-windows\nunif\requirements-torch.txt (line 14)) (11.0.0)
Requirement already satisfied: MarkupSafe>=2.0 in d:\nunif-windows\python\lib\site-packages (from jinja2->torch==2.4.1+cu124->-r D:\nunif-windows\nunif\requirements-torch.txt (line 13)) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\nunif-windows\python\lib\site-packages (from sympy->torch==2.4.1+cu124->-r D:\nunif-windows\nunif\requirements-torch.txt (line 13)) (1.3.0)
Requirement already satisfied: tqdm in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 7)) (4.67.1)
Requirement already satisfied: wand>=0.6.10 in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 8)) (0.6.13)
Requirement already satisfied: fonttools in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 9)) (4.55.0)
Requirement already satisfied: scipy in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 10)) (1.14.1)
Requirement already satisfied: waitress in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 11)) (3.0.2)
Requirement already satisfied: bottle in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 12)) (0.13.2)
Requirement already satisfied: diskcache in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 13)) (5.6.3)
Requirement already satisfied: flake8 in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 14)) (7.1.1)
Requirement already satisfied: psutil in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 15)) (6.1.0)
Requirement already satisfied: pyyaml in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 16)) (6.0.2)
Requirement already satisfied: onnx in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 17)) (1.17.0)
Requirement already satisfied: onnxconverter_common in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 18)) (1.14.0)
Requirement already satisfied: lpips in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 19)) (0.1.4)
Requirement already satisfied: packaging in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 21)) (24.2)
Requirement already satisfied: dctorch in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 24)) (0.1.2)
Requirement already satisfied: timm in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 27)) (1.0.11)
Requirement already satisfied: numba in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 28)) (0.60.0)
Requirement already satisfied: av>=12.2.0 in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 29)) (14.0.0)
Requirement already satisfied: rembg in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 30)) (2.0.60)
Requirement already satisfied: truststore in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements.txt (line 31)) (0.10.0)
Requirement already satisfied: colorama in d:\nunif-windows\python\lib\site-packages (from tqdm->-r D:\nunif-windows\nunif\requirements.txt (line 7)) (0.4.6)
Requirement already satisfied: numpy<2.3,>=1.23.5 in d:\nunif-windows\python\lib\site-packages (from scipy->-r D:\nunif-windows\nunif\requirements.txt (line 10)) (1.26.4)
Requirement already satisfied: mccabe<0.8.0,>=0.7.0 in d:\nunif-windows\python\lib\site-packages (from flake8->-r D:\nunif-windows\nunif\requirements.txt (line 14)) (0.7.0)
Requirement already satisfied: pycodestyle<2.13.0,>=2.12.0 in d:\nunif-windows\python\lib\site-packages (from flake8->-r D:\nunif-windows\nunif\requirements.txt (line 14)) (2.12.1)
Requirement already satisfied: pyflakes<3.3.0,>=3.2.0 in d:\nunif-windows\python\lib\site-packages (from flake8->-r D:\nunif-windows\nunif\requirements.txt (line 14)) (3.2.0)
Requirement already satisfied: protobuf>=3.20.2 in d:\nunif-windows\python\lib\site-packages (from onnx->-r D:\nunif-windows\nunif\requirements.txt (line 17)) (3.20.2)
Requirement already satisfied: torch>=0.4.0 in d:\nunif-windows\python\lib\site-packages (from lpips->-r D:\nunif-windows\nunif\requirements.txt (line 19)) (2.4.1+cu124)
Requirement already satisfied: torchvision>=0.2.1 in d:\nunif-windows\python\lib\site-packages (from lpips->-r D:\nunif-windows\nunif\requirements.txt (line 19)) (0.19.1+cu124)
Requirement already satisfied: huggingface_hub in d:\nunif-windows\python\lib\site-packages (from timm->-r D:\nunif-windows\nunif\requirements.txt (line 27)) (0.26.3)
Requirement already satisfied: safetensors in d:\nunif-windows\python\lib\site-packages (from timm->-r D:\nunif-windows\nunif\requirements.txt (line 27)) (0.4.5)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in d:\nunif-windows\python\lib\site-packages (from numba->-r D:\nunif-windows\nunif\requirements.txt (line 28)) (0.43.0)
Requirement already satisfied: jsonschema in d:\nunif-windows\python\lib\site-packages (from rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (4.23.0)
Requirement already satisfied: opencv-python-headless in d:\nunif-windows\python\lib\site-packages (from rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (4.10.0.84)
Requirement already satisfied: pillow in d:\nunif-windows\python\lib\site-packages (from rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (11.0.0)
Requirement already satisfied: pooch in d:\nunif-windows\python\lib\site-packages (from rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (1.8.2)
Requirement already satisfied: pymatting in d:\nunif-windows\python\lib\site-packages (from rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (1.1.13)
Requirement already satisfied: scikit-image in d:\nunif-windows\python\lib\site-packages (from rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (0.24.0)
Requirement already satisfied: filelock in d:\nunif-windows\python\lib\site-packages (from torch>=0.4.0->lpips->-r D:\nunif-windows\nunif\requirements.txt (line 19)) (3.16.1)
Requirement already satisfied: typing-extensions>=4.8.0 in d:\nunif-windows\python\lib\site-packages (from torch>=0.4.0->lpips->-r D:\nunif-windows\nunif\requirements.txt (line 19)) (4.12.2)
Requirement already satisfied: sympy in d:\nunif-windows\python\lib\site-packages (from torch>=0.4.0->lpips->-r D:\nunif-windows\nunif\requirements.txt (line 19)) (1.13.3)
Requirement already satisfied: networkx in d:\nunif-windows\python\lib\site-packages (from torch>=0.4.0->lpips->-r D:\nunif-windows\nunif\requirements.txt (line 19)) (3.4.2)
Requirement already satisfied: jinja2 in d:\nunif-windows\python\lib\site-packages (from torch>=0.4.0->lpips->-r D:\nunif-windows\nunif\requirements.txt (line 19)) (3.1.4)
Requirement already satisfied: fsspec in d:\nunif-windows\python\lib\site-packages (from torch>=0.4.0->lpips->-r D:\nunif-windows\nunif\requirements.txt (line 19)) (2024.10.0)
Requirement already satisfied: requests in d:\nunif-windows\python\lib\site-packages (from huggingface_hub->timm->-r D:\nunif-windows\nunif\requirements.txt (line 27)) (2.32.3)
Requirement already satisfied: attrs>=22.2.0 in d:\nunif-windows\python\lib\site-packages (from jsonschema->rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (24.2.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in d:\nunif-windows\python\lib\site-packages (from jsonschema->rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (2024.10.1)
Requirement already satisfied: referencing>=0.28.4 in d:\nunif-windows\python\lib\site-packages (from jsonschema->rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (0.35.1)
Requirement already satisfied: rpds-py>=0.7.1 in d:\nunif-windows\python\lib\site-packages (from jsonschema->rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (0.21.0)
Requirement already satisfied: platformdirs>=2.5.0 in d:\nunif-windows\python\lib\site-packages (from pooch->rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (4.3.6)
Requirement already satisfied: imageio>=2.33 in d:\nunif-windows\python\lib\site-packages (from scikit-image->rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (2.36.1)
Requirement already satisfied: tifffile>=2022.8.12 in d:\nunif-windows\python\lib\site-packages (from scikit-image->rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (2024.9.20)
Requirement already satisfied: lazy-loader>=0.4 in d:\nunif-windows\python\lib\site-packages (from scikit-image->rembg->-r D:\nunif-windows\nunif\requirements.txt (line 30)) (0.4)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\nunif-windows\python\lib\site-packages (from requests->huggingface_hub->timm->-r D:\nunif-windows\nunif\requirements.txt (line 27)) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in d:\nunif-windows\python\lib\site-packages (from requests->huggingface_hub->timm->-r D:\nunif-windows\nunif\requirements.txt (line 27)) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\nunif-windows\python\lib\site-packages (from requests->huggingface_hub->timm->-r D:\nunif-windows\nunif\requirements.txt (line 27)) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in d:\nunif-windows\python\lib\site-packages (from requests->huggingface_hub->timm->-r D:\nunif-windows\nunif\requirements.txt (line 27)) (2024.8.30)
Requirement already satisfied: MarkupSafe>=2.0 in d:\nunif-windows\python\lib\site-packages (from jinja2->torch>=0.4.0->lpips->-r D:\nunif-windows\nunif\requirements.txt (line 19)) (3.0.2)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in d:\nunif-windows\python\lib\site-packages (from sympy->torch>=0.4.0->lpips->-r D:\nunif-windows\nunif\requirements.txt (line 19)) (1.3.0)
Requirement already satisfied: wxpython>=4.0.0 in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements-gui.txt (line 1)) (4.2.2)
Requirement already satisfied: pywin32 in d:\nunif-windows\python\lib\site-packages (from -r D:\nunif-windows\nunif\requirements-gui.txt (line 2)) (308)
Requirement already satisfied: six in d:\nunif-windows\python\lib\site-packages (from wxpython>=4.0.0->-r D:\nunif-windows\nunif\requirements-gui.txt (line 1)) (1.16.0)
Requirement already satisfied: numpy in d:\nunif-windows\python\lib\site-packages (from wxpython>=4.0.0->-r D:\nunif-windows\nunif\requirements-gui.txt (line 1)) (1.26.4)
Download Models...
Downloading: "https://github.com/nagadomi/MiDaS_iw3/zipball/master" to D:\nunif-windows\nunif\iw3\pretrained_models\hub\master.zip
Downloading: "https://github.com/nagadomi/ZoeDepth_iw3/zipball/main" to D:\nunif-windows\nunif\iw3\pretrained_models\hub\main.zip
Downloading: "https://github.com/nagadomi/Depth-Anything_iw3/zipball/main" to D:\nunif-windows\nunif\iw3\pretrained_models\hub\main.zip
Downloading: "https://github.com/nagadomi/Depth-Anything_iw3/zipball/main" to D:\nunif-windows\nunif\iw3\pretrained_models\hub\main.zip
Traceback (most recent call last):
  File "runpy.py", line 196, in _run_module_as_main
  File "runpy.py", line 86, in _run_code
  File "D:\nunif-windows\nunif\iw3\gui.py", line 15, in <module>
    from .utils import (
  File "D:\nunif-windows\nunif\iw3\utils.py", line 16, in <module>
    import nunif.utils.video as VU
  File "D:\nunif-windows\nunif\nunif\utils\video.py", line 55, in <module>
    if getattr(Colorspace, "_by_value") and getattr(Colorspace, "_create") and value not in Colorspace._by_value:
  File "enum.py", line 437, in __getattr__
AttributeError: _by_value
Error
Premere un tasto per continuare . . .
`

**Comment by nagadomi** [comment]
Recent update of pyav 14.0.0 is the cause of this problem.
I have fixed it to use the older version (13.1.0), run `update.bat` again.

**Comment by carlobs** [comment]
Problem solved. Thank you
