### ISSUE TITLE
How can i activate the --vr180 flag to the gui for youtube?

### ISSUE THREAD

**Issue by racifesg** [nagadomi/nunif#268]
Hello, thank you for this amazing tool.

I am having difficulty testing my rendered videos in youtube. It comes out to youtube not recognized as VR file.
Using the VR90 aspect ratio turns the video into a fisheye aspect ratio.

I tried using google's metadata injector tool, then subsequently it comes out with a flattened aspect ratio, i believe because the file becomes 32by9 rather than 16by9 in the original video.

I'm wondering if it's possible to have the video processed into a 16by9 VR file for youtube?

I'm looking to achieve a file that displays as flat on flat screens (but with 180 perspective that you can rotate the viewpoint), and becomes VR in the headset.

**Comment by nagadomi** [comment]
Youtube doesn't process my uploaded test video even after a few hours, so my reply may take a few days.

**Comment by nagadomi** [comment]
For Flat SBS (3D anaglyph view),
1. Run `update.bat` (I fixed metadata https://github.com/nagadomi/nunif/commit/403ae23230a31e41414d4297c198fc4171c9c139)
2. Output with `Stereo Format=Half SBS`, `Video Format=mp4`, `Video Codec=libx264` (It seems Full SBS is not supported)
3. Upload to Youtube

For VR180,
1. Output with `Stereo Format=VR90`, `Video Format=mp4`, `Video Codec=libx264`
2. Add side data(metadata) with VR180Creator
3. Upload to Youtube

VR180Creator can be downloaded from 
Windows: https://storage.googleapis.com/vr180-creator/download/VR180_Creator_windows_4.0.0.zip
macOS: https://storage.googleapis.com/vr180-creator/download/VR180_Creator_4.0.0.dmg
Linux: https://storage.googleapis.com/vr180-creator/download/VR180_Creator_linux_4.0.0.tar.gz
I think this is Google's official link. I have only tested Linux version.

VR180Creator (sorry, I could not set locale to English in my env)
![Screenshot from 2024-12-14 03-06-17](https://github.com/user-attachments/assets/4f2d1a08-bd2e-4f74-8c36-34978a98c430)

![Screenshot from 2024-12-14 03-06-48](https://github.com/user-attachments/assets/2987f982-38f2-4d0a-8ed3-4e53519cc62b)

Uploaded video is displayed as flat video immediately after upload, but after a few hours, it will be displayed as VR180 view.
Also, if youtube recognizes the video as VR180, VR180 tag will be added to the video.
![Screenshot from 2024-12-14 02-49-27](https://github.com/user-attachments/assets/3a32627e-4592-4416-85fe-1874a0b73508)

Is this the same step you tried?

**Comment by racifesg** [comment]
Thank you very much for your detailed steps.

I have tested both methods and they both work perfectly in a different way to achieve my goal.

I realized that one of my attempts was similar to method 2, but the vr180 creator tool i was using was outdated.

By the way, i had tested with Video Codec=libx265 for both methods, and it works with method 2, but not method 1. (I believe it's youtube issue).

Thank you once again for your support.

**Comment by nagadomi** [comment]
>By the way, i had tested with Video Codec=libx265 for both methods, and it works with method 2, but not method 1. (I believe it's youtube issue).

libx265 does not have frame-packing option for stereoscopic video frame arrangement.
I don't know if there is a method for making Youtube detect h265 as SBS format.

**Comment by nagadomi** [comment]
I have changed to use frame-packing metadata only for half-sbs.
Because the aspect ratio of Full SBS video with frame-packing option is wrong in Windows Media Player.

I would like to inform you that I have made this change, although it probably does not affect method 1.

**Comment by racifesg** [comment]
Thank you for your kind update. 

I am currently using method 2 for my testing, because the output file is larger size and might be able to trigger 8k on youtube for higher quality (not sure, youtube has not processed my files for 8k yet).

With half sbs for method 1, the output is only 4k which unfortunately does not look as good when viewed on the headset.

I will test method 1 again with your update. Thank you.
