### ISSUE TITLE
No module named 'truststore'

### ISSUE THREAD

**Issue by Wo2U** [nagadomi/nunif#269]
No module named 'truststore'

**Comment by Wo2U** [comment]
ERROR: Ignored the following versions that require a different python version: 0.1.0 Requires-Python >= 3.10; 0.10.0 Requires-Python >=3.10; 0.2.0 Requires-Python >= 3.10; 0.3.0 Requires-Python >= 3.10; 0.4.0 Requires-Python >= 3.10; 0.5.0 Requires-Python >= 3.10; 0.52.0 Requires-Python >=3.6,<3.9; 0.52.0rc3 Requires-Python >=3.6,<3.9; 0.6.0 Requires-Python >= 3.10; 0.6.1 Requires-Python >= 3.10; 0.61.0rc1 Requires-Python >=3.10; 0.7.0 Requires-Python >= 3.10; 0.8.0 Requires-Python >= 3.10; 0.9.0 Requires-Python >=3.10; 0.9.1 Requires-Python >=3.10; 0.9.2 Requires-Python >=3.10; 1.14.0 Requires-Python >=3.10; 1.14.0rc1 Requires-Python >=3.10; 1.14.0rc2 Requires-Python >=3.10; 1.14.1 Requires-Python >=3.10; 1.15.0rc1 Requires-Python >=3.10
ERROR: Could not find a version that satisfies the requirement truststore (from versions: none)
ERROR: No matching distribution found for truststore

**Comment by nagadomi** [comment]
Perhaps it's python version or OS problem.
What is your python version and OS?

Also, there are no major problems without truststore, so if there are installation problems in a particular environment, I can change to work without truststore.

**Comment by nagadomi** [comment]
Python versions less than 3.10 are not supported.
But except for truststore, it probably works with 3.9. 3.8 is really not supported.

**Comment by Wo2U** [comment]
windows11 latest official version, python 3.13. the problem is that after using the latest iw3 to remove the truststore installation environment startup does not appear gui, cmd once appeared to disappear!

**Comment by Wo2U** [comment]
windows11 latest official version, python 3.9.13. the problem is that after using the latest iw3 to remove the truststore installation environment startup does not appear gui, cmd once appeared to disappear!

**Comment by nagadomi** [comment]
I updated the master branch to work without truststore. Try again after git pull.

However, I am not sure if this repo will work with python 3.9.
nunif-windows-package contains Embeddable Python 3.10.11, 3.9 is not used.
