### ISSUE TITLE
Output is only a 2d file

### ISSUE THREAD

**Issue by Nachttraum1966** [nagadomi/nunif#271]
Hello,
I started with testing iw3. Before I work with owl 3d. Now I have the problem that in Iw3 the output file is never a sbs file. The output file is always a 2d file. What is my mistake?

**Comment by nagadomi** [comment]
If you have selected `Stereo Format=Full SBS` (by default), the output video will be side-by-side layout.
Make sure the video you are checking is `Output` file path (folder), not the source video.

**Comment by Nachttraum1966** [comment]
No sorry I don't get a side-by-side file as an output
![17342921746151913289027241037264](https://github.com/user-attachments/assets/35b65fe5-fbaf-4a1e-ae4a-9cb79ce6bd23)

**Comment by Nachttraum1966** [comment]
That's how my output file looks
![17342923757188590139509135254424](https://github.com/user-attachments/assets/7416daaf-dbfa-4a92-8f7f-16d9cd770675)

**Comment by nagadomi** [comment]
Could you check the playback in web browser? (Drag and drop to play)
I added the metadata for half SBS yesterday, so some video players may be showing it in 2D

**Comment by nagadomi** [comment]
Confirmed.
It is shown in 2D by Windows Photo.
Try playing it with Windows Media Player.

**Comment by Nachttraum1966** [comment]
You are right. With vlc player I see an side by side file. 

⁣BlueMail for Android herunterladen ​

**Comment by nagadomi** [comment]
I will add this problem to the troubleshooting section of the README.

**Comment by Nachttraum1966** [comment]
It's OK for me

⁣BlueMail for Android herunterladen ​
