### ISSUE TITLE
Request: Anyway to run batch export disparity bitmaps

### ISSUE THREAD

**Issue by Gamer4Life2020** [nagadomi/nunif#272]
I was wondering if there was any to batch export disparity bitmaps from a folder. I have tired DepthAnythingV2 and to edit with chatgpt as I don't know programming. I did work but is much slower and lower quality. Not sure what you changed but iw3 is better the DepthAnytingV2 for speed and quality. If not no problem just though I would ask and I'll just do one at a time.

**Comment by nagadomi** [comment]
See https://github.com/nagadomi/nunif/issues/97#issuecomment-2027349722
Summary: Use `Stereo Format=Export disparity`

If you are already know this feature, please describe specifically what feature is missing.
I am not sure if the request is for batch processing for video, BITMAP image format, or if you do not know about the Export feature.
Batch export for image folder is already supported.

**Comment by Gamer4Life2020** [comment]
I don't know that is missing per say I can't get it to work in iw3 if it's supported. I have tired selecting a directory with several files and selecting a different output. When ran it goes straight to finished and the depth folder is empty.
<img width="1435" alt="iw3 batch" src="https://github.com/user-attachments/assets/d0e72799-006c-4655-afc1-8c0c006eaa2c" />

**Comment by nagadomi** [comment]
When directory is specified, only image files are processed. video files are not processed.
Batch export for video folder is currently not supported.

**Comment by Gamer4Life2020** [comment]
Ok thanks, I'll convert to PNG and go from there.

**Comment by nagadomi** [comment]
Are those files image files? I don't know the format of the file because the file extension is not shown. I assumed they were video files.

**Comment by Gamer4Life2020** [comment]
They where .mkv video files not jpg/png. I'll just use Resolve to make to PNGs.

**Comment by nagadomi** [comment]
Export feature does not support recursive processing of folders.

Only the following inputs are supported
- single video file
- single image file
- flat image folder (subdirectories are not processed)

So, currently there is no way to process multiple videos at once.
