### ISSUE TITLE
[unlimited:waifu2x] AlphaBorderPadding

### ISSUE THREAD

**Issue by nagadomi** [nagadomi/nunif#32]
alpha_border_padding(related to the handling of transparent PNG) is not fully working on unlimited:waifu2x.
ONNX model output is different between Python and JavaScript version, resulting in jagged border with transparent area.

related:
https://github.com/nagadomi/waifu2x/issues/197#issuecomment-1531036741
to several comments

**Comment by nagadomi** [comment]
This seems to be fixed already.
Probably due to some change of ONNX exporter on PyTorch side.

**Comment by nagadomi** [comment]
I have tried with other images, and still have problems

**Comment by nagadomi** [comment]
**About AlphaBorderPadding**
AlphaBorderPadding pads RGB values of fully transparent areas (alpha channel=0).
Even fully transparent areas have RGB values.
But it is generally never displayed to users, so it has unstable values, such as fixed values, color palettes, signatures, uninitialized values, etc.
So convolving an image without AlphaBorderPadding may cause artifacts on the alpha border.

Examples:
input
![Mozilla_Firefox_3 5_logo](https://user-images.githubusercontent.com/287255/236735328-cb3a5282-1ee6-41ca-b036-49aa49746111.png)
rgb
![Mozilla_Firefox_3 5_logo_rgb](https://user-images.githubusercontent.com/287255/236735493-904f5589-573e-4294-b849-81eb60369527.png)
padded
![Mozilla_Firefox_3 5_logo_pad](https://user-images.githubusercontent.com/287255/236735530-0ed77a38-c73e-48c0-95cd-7f2ea8bc551b.png)

input
![gimp-icon](https://user-images.githubusercontent.com/287255/236735570-a98bb75d-1389-43c7-ba5c-aa4e8a4929ad.png)
rgb
![gimp-icon_rgb](https://user-images.githubusercontent.com/287255/236735587-bbe1b811-6b2f-4361-8315-0ea74e2ad221.png)
padded

![gimp-icon_pad](https://user-images.githubusercontent.com/287255/236735614-580ebe6a-db4f-4343-94e8-d05da57dd2d3.png)

input
![blender_icon_256x256](https://user-images.githubusercontent.com/287255/236735727-38445c92-03a0-4b71-8251-9710f1206ff0.png)
rgb

![blender_logo_rgb](https://user-images.githubusercontent.com/287255/236735754-c01b52ba-f699-496f-9b73-879c1c2e7571.png)

padded
![blender_logo_pad](https://user-images.githubusercontent.com/287255/236735773-f9cff595-0f67-47a0-83e8-7a3b9ab11e2a.png)

**Comment by nagadomi** [comment]
copy from https://github.com/nagadomi/nunif/issues/36#issuecomment-1537748115

And there still seems to be a problem.
The output of the Blender logo is as follows in unlimited:waifu2x.
![alpha_border_pad_onnx](https://user-images.githubusercontent.com/287255/236737083-a508cbaf-fdde-446d-8879-f8f3a1f9cf59.png)
There is a strange strong red line. (ignore reflection padding).

pytorch version output
![blender_logo_pad](https://user-images.githubusercontent.com/287255/236737604-c688e4fd-ee09-4173-a25b-6216dd895713.png)


Change `script.js` as follows to show the result of AlphaBorderPadding.
```diff
         // create temporary canvas for tile input
-        image_data = this.to_image_data(x.data, alpha3.data, x.dims[3], x.dims[2]);
+        image_data = this.to_image_data(x.data, null, x.dims[3], x.dims[2]);
         var input_canvas = document.createElement("canvas");
         input_canvas.width = w;
         input_canvas.height = h;
         var input_ctx = input_canvas.getContext("2d", {willReadFrequently: true});
         input_ctx.putImageData(image_data, 0, 0);
+        document.body.appendChild(input_canvas);
         var all_blocks = p.h_blocks * p.w_blocks;
 
         // tiled rendering
```

**Comment by nagadomi** [comment]
Additionally, using the Python version of onnxruntime, it shows correctly.

![ed0486d351699b1255a03145ca08cb43](https://user-images.githubusercontent.com/287255/236740623-4b934e7c-dc03-4a39-b9ef-7d31975347af.png)

I change the file name and offset=8 in https://github.com/nagadomi/nunif/blob/d5ede7b19d57528c4e01c78ca8459a181edcd825/nunif/models/onnx_helper_models.py#L310-L347 and run it.

**Comment by LoganDark** [comment]
> Additionally, using the Python version of onnxruntime, it shows correctly.
> 
> ![ed0486d351699b1255a03145ca08cb43](https://user-images.githubusercontent.com/287255/236740623-4b934e7c-dc03-4a39-b9ef-7d31975347af.png)
> 
> I change the file name and offset=8 in
> 
> https://github.com/nagadomi/nunif/blob/d5ede7b19d57528c4e01c78ca8459a181edcd825/nunif/models/onnx_helper_models.py#L310-L347
> 
> and run it.

What if you use the CPU execution provider from Python?

**Comment by nagadomi** [comment]
I tried `CPUExecutionProvider` and it works correctly.
![2f1028cc03d47482682b8846cd986cf8](https://user-images.githubusercontent.com/287255/236826652-93717468-9f23-4b3d-a948-dff60fa6e4b0.png)

---
This problem can have two major causes.
1. pixel values of images returned from Canvas
2. ONNXRuntime execution providers

The hard part of this problem is that I don't know what is happening in `Python->TorchScript->ONNX` process.
The easiest solution is to reimplement AlphaBorderPadding in pure JavaScript.

**Comment by LoganDark** [comment]
> The easiest solution is to reimplement AlphaBorderPadding in pure JavaScript.

I actually just finished doing this and it looks like the problem might be something like canvas using premultiplied alpha internally

**Comment by LoganDark** [comment]
![image](https://user-images.githubusercontent.com/4723091/236833129-23dd0450-e226-4850-b9db-8d3f3297e516.png)
See these artifacts on the rgb input when it is not bled
I am not sure where these come from, but if I import an output (with no model or padding or bleeding) into an image editor you can see dark edges indicative of premultiplication
![image](https://user-images.githubusercontent.com/4723091/236833433-28ed4a09-11e2-443a-9382-6c348950f8b4.png)
which is probably lowering precision and if I removed the alpha channel in my image editor you can see it looks pretty premultiplied

![image](https://user-images.githubusercontent.com/4723091/236833605-96832a12-c8e0-42bb-a2e6-779f4db85063.png)

there are parameters that can be used to combat this I will run some experiments

**Comment by nagadomi** [comment]
If `putImageData` is the cause, then implementing `crop(x, y, width, height)` for `Float32Array` without creating a temporary canvas will work fine.
However, if the pixel values are already broken at 
https://github.com/nagadomi/nunif/blob/d5ede7b19d57528c4e01c78ca8459a181edcd825/waifu2x/unlimited_waifu2x/public_html/script.js#L640-L651
, then PNG decoder without Canvas is needed.

**Comment by LoganDark** [comment]
> If `putImageData` is the cause, then implementing `crop(x, y, width, height)` for `Float32Array` without creating a temporary canvas will work fine. However, if the pixel values are already broken at
> 
> https://github.com/nagadomi/nunif/blob/d5ede7b19d57528c4e01c78ca8459a181edcd825/waifu2x/unlimited_waifu2x/public_html/script.js#L640-L651
> 
> 
> , then PNG decoder without Canvas is needed.

See the reply I just made. WebGL1 works. But you need to be able to process the input data without tripping through canvas. This is only possible within my rewritten codebase that uses ImageBitmap and ImageData.

**Comment by nagadomi** [comment]
Thank you. I understand the cause of this problem and some solutions.

>The solution is, instead of using all pixels with an alpha above 0, define the boundary to be something like 0.5.

It may depend on the implementation, but changing pixel values other than alpha 0 will affect the visibility of the image. 
If it is just for reference, no problem.
In a face image dataset I saw, it applied blur filter to the padded pixels to prevent jaggedness.
(appling blur filter to the entire image and then mask it with alpha==0.)

**Comment by LoganDark** [comment]
> changing pixel values other than alpha 0 will affect the visibility of the image

This is true, but so will upscaling itself.

Maybe it should be adjustable.

**Comment by nagadomi** [comment]
Sometimes the quality of the alpha channel is not good enough, so it might be useful to be able to fix it, but it is not a problem with waifu2x.
What does not work is the case where the alpha channel of the entire image is such that alpha = 0.1.

**Comment by LoganDark** [comment]
> What does not work is the case where the alpha channel of the entire image is such that alpha = 0.1.

Yes, indeed. User adjustability would be needed in that case.

**Comment by LoganDark** [comment]
I found a way to avoid the premultiplication on saving too.

upscaled result:

![haie](https://github.com/nagadomi/nunif/assets/4723091/7dd6df04-126c-4c36-8c9c-f8fe08f44086)

alpha channel removed (except for transparent black):

![haie2](https://github.com/nagadomi/nunif/assets/4723091/f8d33b70-cb42-4bb3-814c-6d72b6c395ed)

(ignore the missing spots - I do edge bleeding on individual tiles to reduce memory pressure, I never convert the entire image to a tensor)

job summary:

```
―――― unlimited:waifu2x job completed ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
· Input: 560x560 (313600px)
· Output: 1120x1120 (1254400px)
· Model: cunet.art
· Denoise: 3
· Scale: 2
· Tile size: 64
· TTA level: 0
· Alpha: true
· Threads: 12


→ run: 8860.85ms
	→ run.canvas: 0.80ms
		→ run.canvas.getContext: 0.00ms
		→ run.canvas.clear: 0.00ms
		→ run.canvas.backdrop: 0.79ms
	→ run.glReader: 13.96ms
		→ run.glReader.input: 5.32ms
		→ run.glReader.output: 8.59ms
	→ run.tiledRender: 8845.63ms
		→ run.tiledRender.collectTiles: 8835.88ms
			→ run.tiledRender.collectTiles.calculateTotalPixels: 0.03ms
			→ run.tiledRender.collectTiles.newScratch: 0.02ms
			→ run.tiledRender.collectTiles.tile: 81 occurrences; min 75.67ms, max 331.64ms, avg 109.08ms, total 8835.56ms
				→ run.tiledRender.collectTiles.tile.pick: 81 occurrences; min 0.00ms, max 0.01ms, avg 0.01ms, total 0.54ms
				→ run.tiledRender.collectTiles.tile.calculateTileMetrics: 81 occurrences; min 0.00ms, max 0.07ms, avg 0.00ms, total 0.35ms
				→ run.tiledRender.collectTiles.tile.reportCallbackStarted: 81 occurrences; min 0.01ms, max 0.23ms, avg 0.02ms, total 1.77ms
				→ run.tiledRender.collectTiles.tile.indicator: 81 occurrences; min 0.00ms, max 0.04ms, avg 0.01ms, total 0.71ms
				→ run.tiledRender.collectTiles.tile.capture: 81 occurrences; min 1.10ms, max 24.37ms, avg 3.86ms, total 312.46ms
				→ run.tiledRender.collectTiles.tile.process: 81 occurrences; min 72.36ms, max 326.75ms, avg 104.85ms, total 8492.89ms
					→ run.tiledRender.collectTiles.tile.process.toRgbAlpha: 81 occurrences; min 0.06ms, max 0.83ms, avg 0.14ms, total 11.48ms
					→ run.tiledRender.collectTiles.tile.process.bleedEdges: 81 occurrences; min 0.04ms, max 4.04ms, avg 0.38ms, total 31.05ms
					→ run.tiledRender.collectTiles.tile.process.stretchAlpha: 81 occurrences; min 0.01ms, max 0.33ms, avg 0.05ms, total 3.76ms
					→ run.tiledRender.collectTiles.tile.process.pad: 81 occurrences; min 0.57ms, max 10.12ms, avg 1.48ms, total 120.03ms
						→ run.tiledRender.collectTiles.tile.process.pad.rgb: 81 occurrences; min 0.32ms, max 9.82ms, avg 1.07ms, total 86.34ms
						→ run.tiledRender.collectTiles.tile.process.pad.alpha: 81 occurrences; min 0.20ms, max 3.49ms, avg 0.40ms, total 32.75ms
					→ run.tiledRender.collectTiles.tile.process.model: 81 occurrences; min 70.40ms, max 306.33ms, avg 102.46ms, total 8299.40ms
						→ run.tiledRender.collectTiles.tile.process.model.batch: 81 occurrences; min 0.03ms, max 0.17ms, avg 0.09ms, total 7.29ms
						→ run.tiledRender.collectTiles.tile.process.model.run: 81 occurrences; min 70.13ms, max 306.07ms, avg 102.21ms, total 8279.30ms
						→ run.tiledRender.collectTiles.tile.process.model.unbatch: 81 occurrences; min 0.05ms, max 0.50ms, avg 0.14ms, total 11.65ms
					→ run.tiledRender.collectTiles.tile.process.rgbToImageData: 81 occurrences; min 0.17ms, max 5.31ms, avg 0.32ms, total 25.86ms
				→ run.tiledRender.collectTiles.tile.crop: 81 occurrences; min 0.04ms, max 0.23ms, avg 0.06ms, total 5.03ms
				→ run.tiledRender.collectTiles.tile.writePixels: 81 occurrences; min 0.02ms, max 0.10ms, avg 0.07ms, total 5.29ms
				→ run.tiledRender.collectTiles.tile.clearRect: 81 occurrences; min 0.00ms, max 0.06ms, avg 0.01ms, total 1.05ms
				→ run.tiledRender.collectTiles.tile.drawImage: 81 occurrences; min 0.07ms, max 0.61ms, avg 0.09ms, total 7.44ms
				→ run.tiledRender.collectTiles.tile.updateCounters: 81 occurrences; min 0.00ms, max 0.01ms, avg 0.00ms, total 0.10ms
				→ run.tiledRender.collectTiles.tile.reportCallbackCompleted: 81 occurrences; min 0.06ms, max 0.21ms, avg 0.07ms, total 5.61ms
		→ run.tiledRender.readPixels: 7.74ms
		→ run.tiledRender.outputBitmap: 1.99ms
――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
```

Here is the result from official unlimited:waifu2x:

![hai_waifu2x_noise3_scale2x](https://github.com/nagadomi/nunif/assets/4723091/6f7170d8-d73d-490e-bad2-7caf4bedf2b6)

![hai_waifu2x_noise3_scale2xe](https://github.com/nagadomi/nunif/assets/4723091/9f7a8c78-676a-491b-b9dd-20e4743d838d)

this is because it is saving the premultiplied data in the output canvas instead of using a hack to smuggle non-premultiplied data into the canvas. This is actually possible using `bitmaprenderer` context, you can upload a non-premultiplied `ImageBitmap` to the canvas, and convert it to a blob, and it will be completely lossless.

I use an offscreen canvas for this because you can't mix multiple contexts in a canvas, but also because uploading the non-premultiplied data has an undesirable visual effect as well. Best only to use it for downloads.

I wonder how many online image processors actually do not take into account the alpha premultiplication, it must be a lot. It's very difficult to avoid. I might be the only person who cares

**Comment by nagadomi** [comment]
Fixed by https://github.com/nagadomi/nunif/commit/2bbdef93fab6ed5e42ad84c37f77e41ea4698f7c  ← https://github.com/nagadomi/nunif/commit/55ce24be1408da35c9b64aa4c5278d75950a1797 ← https://github.com/nagadomi/nunif/commit/8136f645ed4ce905d26ec7662292c703183934ff
Thank you for all your help.

I changed the top input image area from Canvas to HTMLImageElement and decoded img with WebGL when upscaling is executed.
In tiled_render, tile image is cropped from tensor without using temporary Canvas.
