### ISSUE TITLE
Is there a reason for 4x not being available?

### ISSUE THREAD

**Issue by luiscla27** [nagadomi/nunif#33]
I noticed that `https://unlimited.waifu2x.net` has `4x` but the one from this repository is not, thank you.

![chrome_GpQxac4LsP](https://user-images.githubusercontent.com/29953012/235843109-b5e434a8-96e9-4c5f-886e-7ec0899784ea.png)

**Comment by luiscla27** [comment]
I just discovered this, so nvm:
https://github.com/nagadomi/nunif/blob/master/waifu2x/unlimited_waifu2x/README.md

**Comment by nagadomi** [comment]
Currently 4x is only supported in command line tool(CLI) and in-browser version(unlimited:waifu2x).
The reason there is no 4x in the web server version is due to the image transfer fee on the web site (waifu2x.udp.jp).

However, it can be supported for running the web server version locally.
