### ISSUE TITLE
[unlimited:waifu2x] What is the purpose of alpha_border_padding?

### ISSUE THREAD

**Issue by LoganDark** [nagadomi/nunif#36]
I am wondering what the purpose is of `alpha_border_padding`, because it doesn't seem like it does anything (at least the ONNX version of it).

I thought it was doing [color bleeding](https://www.adriancourreges.com/blog/2017/05/09/beware-of-transparent-pixels/#as-an-artist-make-it-bleed), but during the course of my (personal) rewrite, I checked the output of `alpha_border_padding` and it seems to be completely identical to the input, no matter which offset value I choose.

What is the purpose of this model?

**Comment by nagadomi** [comment]
Yes, it is for the same purpose you mention.
I posted descriptions and examples on https://github.com/nagadomi/nunif/issues/32#issuecomment-1537737645

And there still seems to be a problem.
The output of the Blender logo is as follows in unlimited:waifu2x.
![alpha_border_pad_onnx](https://user-images.githubusercontent.com/287255/236737083-a508cbaf-fdde-446d-8879-f8f3a1f9cf59.png)
There is a strange strong red line. (ignore reflection padding).

pytorch version output
![blender_logo_pad](https://user-images.githubusercontent.com/287255/236737604-c688e4fd-ee09-4173-a25b-6216dd895713.png)


Change `script.js` as follows to show the result of AlphaBorderPadding.
```diff
         // create temporary canvas for tile input
-        image_data = this.to_image_data(x.data, alpha3.data, x.dims[3], x.dims[2]);
+        image_data = this.to_image_data(x.data, null, x.dims[3], x.dims[2]);
         var input_canvas = document.createElement("canvas");
         input_canvas.width = w;
         input_canvas.height = h;
         var input_ctx = input_canvas.getContext("2d", {willReadFrequently: true});
         input_ctx.putImageData(image_data, 0, 0);
+        document.body.appendChild(input_canvas);
         var all_blocks = p.h_blocks * p.w_blocks;
 
         // tiled rendering
```

**Comment by LoganDark** [comment]
> The output of the Blender logo is as follows in unlimited:waifu2x.

![image](https://user-images.githubusercontent.com/4723091/236802697-53bcfa23-e74b-4dce-b54b-c0776eab594b.png)

I am not sure what is wrong with your code, but in my rewritten version, it works fine.

**Comment by LoganDark** [comment]
Okay yeah, I can see that issue on my version too:

![image](https://user-images.githubusercontent.com/4723091/236809306-0edec55f-f956-4598-992f-afa4549155a0.png)

I plan to replace alpha border padding because of it sucking

**Comment by LoganDark** [comment]
Closing this issue because it has been answered
