### ISSUE TITLE
waifu2x caffe issue installing

### ISSUE THREAD

**Issue by BBLOVERl** [nagadomi/nunif#37]
hey im having issue installing waifu2x caffe. I am able to download it but when i go to use it, it gives me an error saying how i didn't install it? can someone help?

**Comment by Nergis-Dev** [comment]
The repo you are looking for is https://github.com/lltcggie/waifu2x-caffe.

**Comment by nagadomi** [comment]
Yes, this is not the repository of waifu2x-caffe.
You do not need to install waifu2x-caffe. Download and unzip waifu2x-caffe.zip file from https://github.com/lltcggie/waifu2x-caffe/releases and run the exe
