### ISSUE TITLE
[suggestion] A Browser Extension

### ISSUE THREAD

**Issue by hell1231** [nagadomi/nunif#39]
Here how I think the extension should work
After a website that contains images loads completely, the extension will work automatically to enhance these images and replace them with the old images.
the first option would be enhance by using the cloud
the second would be be enhance by using the pc itself

**Comment by nagadomi** [comment]
Duplicated. See https://github.com/nagadomi/waifu2x/discussions/446
If you have any other suggestions, post to https://github.com/nagadomi/nunif/discussions/28
