### ISSUE TITLE
The ability to scale not only photos but also websites.

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#41]
- [ ] Magnification of photos on websites.
- [x] Save enlarged images for quick output when repeated request. Make it possible at will using some argument --. To determine repeated requests, use the hash of the image.

![2023-06-05_16-15-52](https://github.com/nagadomi/nunif/assets/49092250/9050be81-7cad-4d3c-bd30-3b3611a7e52f)

**Comment by nagadomi** [comment]
Usually more than 1000 people visit waifu2x.udp.jp at the same time.
So it is not allowed to take a lot of time for one request.

Also, currently images are cached for 30 minutes, and that is more than 10GB in 30 minutes.
So it is not allowed to keep caches for long hours.

**Comment by nagadomi** [comment]
>Where are the processed images stored in the local version?

You can specify it with `--cache-dir` option, `tmp/waifu2x_cache` by default.
Also, you can specify the expiration time of the cache with the following option. ( 30 minutes by default)
```
--cache-ttl CACHE_TTL
                        cache TTL(min) (default: 30)
```
However, cache files are [diskcache](https://pypi.org/project/diskcache/) format so they cannot be viewed with common image viewers.

>Is it possible to do this for the local version?

All you need is a web crawler (scraper) software. You should use another software for that purpose.

1. Crawling images with crawler software
2. Processing images with waifu2x CLI

**Comment by My12123** [comment]
> All you need is a web crawler (scraper) software. You should use another software for that purpose.
> Downloading images with crawler software
> Processing images with waifu2x CLI

How can this be done?
I found a crawler https://github.com/BruceDone/awesome-crawler

**Comment by My12123** [comment]
https://github.com/1j01/rezzy-zoom-and-enhance
I found this but it doesn't really help the Art/Scans model is better suited for manga.

**Comment by nagadomi** [comment]
>Will a waifu2x crawler version be created?

I will not develop it.
