### ISSUE TITLE
Way too slow

### ISSUE THREAD

**Issue by mrlnfiniti** [nagadomi/nunif#43]
I don't know If I did something incorrectly but it works but way way too slow, I'm talking about trying x2 a 7MB pic and waiting for +45m and still nothing. Tried with a really low resolution one, like 70KB and it worked fine, still waited for like 5m.
I'm using ubuntu from the microsoft workshop and did the full installation but ImageMagick. I don't have a top shape PC but still fairly decent. Using the web localhost version. Any advice?

**Comment by nagadomi** [comment]
This code can be run on Windows.
There is no need to use WSL(ubuntu on windows).
I have never tried WSL. However, I see a number of reports of pytorch/jax CUDA backend on WSL is very slow, so maybe that is the cause.

**Comment by mrlnfiniti** [comment]
How would you run the code on windows without WSL then?

**Comment by guibos** [comment]
https://github.com/nagadomi/nunif/blob/master/INSTALL-windows.md

**Comment by nagadomi** [comment]
Yes, it can run on Anaconda Python env.

**Comment by mrlnfiniti** [comment]
Okay I've done the env, and it's working perfectly, thank you very much. Anyway I can add the x4 resolution in the web application?

**Comment by mrlnfiniti** [comment]
Oh and, is there a way to see how far is the proccess going?

**Comment by nagadomi** [comment]
Is the error only happening with large images?
Could you post the entire message in the first image?

>big pic (76MB)

What is the image size in pixels?

----

In the last image, you seem to be specifying `--gpu 1`(second GPU). If you want to use GPU 0, use `--gpu 0`, if you want to use CPU, use `--gpu -1`. 

---

If you have not installed the GPU driver manually, try the official NVIDIA driver.
https://www.nvidia.com/download/index.aspx

**Comment by mrlnfiniti** [comment]
The erros is only happening with large images yeah. 
Nothing out of that image IIRC, just the prompt.
The image is 6000x8000px. 
Just updated my GPU Driver with that link, and restarted the PC, still the same issue.
![image](https://github.com/nagadomi/nunif/assets/135876436/6661332e-0e0e-4a5d-a351-09e82ae26c5f)

**Comment by nagadomi** [comment]
>The erros is only happening with large images yeah.
>![](https://user-images.githubusercontent.com/135876436/246892975-e9a267f6-0512-45f8-87d9-611191dd9d24.png)

Is this information about when using cpu mode (`--gpu -1`)?
I guess this is an out-of-memory error. Not related to the GPU driver, I think. 

---
For GPU issues,

What error message would you get with the following command?
```
python -c "import torch; torch.zeros(1).cuda()"
```

If you get "AssertionError: Torch not compiled with CUDA enabled" error, install pytorch using the install command with CUDA selected, as follows
https://pytorch.org/get-started/locally/
![9061ed817e135bfcd5c1cfd4e3e9517a](https://github.com/nagadomi/nunif/assets/287255/2fb8dea1-04d8-4e86-a695-1e4422aee5b6)

**Comment by mrlnfiniti** [comment]
![image](https://github.com/nagadomi/nunif/assets/135876436/44046705-e2fb-48ed-afef-6da14f96664b)
Still the same error...

**Comment by nagadomi** [comment]
What error message?
`python -c "import torch; torch.zeros(1).cuda()"`
Is it really "AssertionError: Torch is not compiled with CUDA enabled"?

**Comment by nagadomi** [comment]
Anaconda may have multiple pytorch installations, conda and pip repositories and default env and env.
Try rebuilding the env.
```
conda deactivate
conda remove --name nunif --all
conda create -n nunif
conda activate nunif
conda install pytorch torchvision torchaudio pytorch-cuda=11.8 -c pytorch -c nvidia
pip3 install -r requirements.txt
```
You have to run `conda activate nunif` every time you want to enter the virtual env.

---
After trying the above, if you still have same problems, try the pip version of pytorch instead of conda.
This is suggested as possible solution in [AssertionError: Torch not compiled with CUDA enabled](https://github.com/pytorch/pytorch/issues/30664)

```
conda uninstall pytorch torchvision torchaudio pytorch-cuda
pip uninstall torch torchvision torchaudio
pip cache purge
pip3 install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu118
pip3 install -r requirements.txt
```

Also, this is a problem of pytorch and conda's environment, not of this repository. See also https://github.com/pytorch/pytorch/issues/30664

**Comment by mrlnfiniti** [comment]
Okay, thank you very much! I'm using now the waifu.cli for upgrading whole folders and it works like a charm, really nice software!
