### ISSUE TITLE
Improve the installation for windows

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#44]
Instead of anaconda, it is better to use venv

Even better if this code will be executed by itself. I have a problem with running commands in venv is it possible to fix it?
Installation code for windows

```
# Install python 3.10
python -m venv venv
cd .\nunif\venv\Scripts
activate.bat
cd .. # move one directory back
cd ..
pip3 install torch torchvision torchaudio torchtext --index-url https://download.pytorch.org/whl/cu116
pip install -r requirements.txt
python -m waifu2x.download_models
python -m waifu2x.web.webgen
```
Startup code for windows

```
cd .\venv\Scripts
activate.bat
cd .. # move one directory back
cd ..
python -m waifu2x.web --no-size-limit --tile-size 400
```

I usually run using the commands
```
F:
cd F:\nunif
cd .\venv\Scripts
activate.bat
cd ..
cd ..
python -m waifu2x.web --no-size-limit --cache-ttl 120 --cache-dir F:\nunif\waifu2x\cache --tile-size 400
```

**Comment by nagadomi** [comment]
Yes, it is better not to use the conda package manager if you can avoid using it. However, there are some modules that are only available on conda repository (It is not currently in nunif's dependency modules).

---
> I have a problem with running commands in venv is it possible to fix it?

What is the problem?


>```
>cd .\nunif\venv\Scripts
>activate.bat
>cd .. # move one directory back
>cd ..
>```
This part can be done on one line. `nunif\venv\Scripts\activate`

Here is an example of `run-web.bat`
```
cd /d F:\nunif
.\venv\Scripts\activate
python -m waifu2x.web --no-size-limit --cache-ttl 120 --cache-dir F:\nunif\waifu2x\cache --tile-size 400
```

**Comment by My12123** [comment]
![2023-06-25_18-16-52](https://github.com/nagadomi/nunif/assets/49092250/4f22452f-e0ba-4ad2-be88-50a8ac92ce27)
The command is not executed `python -m waifu2x.web --no-size-limit --cache-ttl 120 --cache-dir F:\nunif\waifu2x\cache --tile-size 400`
How do I make run-web.bat not close?

**Comment by nagadomi** [comment]
It seems that "call" is needed to run activate.bat.
```
cd /d F:\nunif
call .\venv\Scripts\activate
python -m waifu2x.web --no-size-limit --cache-ttl 120 --cache-dir F:\nunif\waifu2x\cache --tile-size 400
pause
```

**Comment by My12123** [comment]
https://github.com/nagadomi/nunif/pull/46

**Comment by My12123** [comment]
https://github.com/nagadomi/nunif/pull/48
