### ISSUE TITLE
Video Processing

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#45]
Video processing by different models

**Comment by nagadomi** [comment]
waifu2x models are not designed for video processing. They are not trained on video codec degradation.
If you still want to try it, [vs-mlrt](https://github.com/AmusementClub/vs-mlrt) seems to support all waifu2x models and other ML models. (I have not tried that yet.)

**Comment by My12123** [comment]
Will it be fixed?

**Comment by nagadomi** [comment]
No plans at this time.

**Comment by nagadomi** [comment]
I am currently developing a tool to convert any 2D video to side-by-side 3D video.
For that work, I plan to add the functions to load and encode video.
Not sure if it will support super resolution.

**Comment by My12123** [comment]
When will it be ready to launch?

**Comment by My12123** [comment]
@nagadomi

**Comment by nagadomi** [comment]
I released it.
I understood how to process videos with pyav.
However, there is no support for waifu2x yet.

**Comment by My12123** [comment]
I am interested in the Artwork/Scans model

**Comment by nagadomi** [comment]
video input/output is now supported in waifu2x.cli.
See example in https://github.com/nagadomi/nunif/blob/master/waifu2x/docs/cli.md#video-processing
