### ISSUE TITLE
pythonw?

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#51]
![2023-07-14_17-58-55](https://github.com/nagadomi/nunif/assets/49092250/622f17fb-70eb-4467-8656-2205f7e6f361)
![2023-07-14_18-01-55](https://github.com/nagadomi/nunif/assets/49092250/70708016-8c8e-438a-b345-c494b86d3e68)

**Comment by MattBuilt1** [comment]
@My12123 How did you solve this problem?  I am getting the same error.
