### ISSUE TITLE
How to train an Artwork/Scans model?

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#52]

**Comment by nagadomi** [comment]
commands and options I used for training are found in waifu2x/appendix

1. train PSNR optimized model(art_scan_psnr) finetuning from pretrained_models/swin_unet/art/
https://github.com/nagadomi/nunif/blob/master/waifu2x/appendix/train_art_scan_psnr.sh
2. train art_scan model with GAN finetuning from PSNR optimized model(art_scan_psnr)
https://github.com/nagadomi/nunif/blob/master/waifu2x/appendix/train_art_scan_gan.sh

Also, screentone training data is generated by https://github.com/nagadomi/nunif/blob/master/waifu2x/training/screentone_generator.py

I do not recommend this to average users.
Maybe it is not easy to achieve good results, and supporting it is also hard.

**Comment by My12123** [comment]
Is there a version for Windows?

**Comment by nagadomi** [comment]
No. It is reference material.
