### ISSUE TITLE
libraqm‑0.7.1.dll.zip 下载地址失效了，有云盘下载地址吗？ https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow

### ISSUE THREAD

**Issue by nissansz** [nagadomi/nunif#54]
libraqm‑0.7.1.dll.zip 下载地址失效了，有云盘下载地址吗？ https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow

**Comment by nagadomi** [comment]
I see that you have resolved the issue in pillow repository. https://github.com/python-pillow/Pillow/issues/7337
The documentation in this repository seems to be out of date.
I will fix it next time.

**Comment by nissansz** [comment]
Thank you.
