### ISSUE TITLE
[Function query] Anime Restoration

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#55]
- [x] Scaling and noise reduction of Artwork/Skins with an increase in the number of frames.
- [ ] AI will redraw old anime and manga into a new style (a more modern image).

**Comment by nagadomi** [comment]
I'm not interested in either.

>increase frames

This feature is called `Video Frame interpolation`. You can find various software for it.

>redraw

This would be difficult to achieve practical application.
Without the consistency of multiple characters and series, it would be possible with ControlNet.

Also, I will not develop features that intentionally ruin other people's artwork.
For generative art, I believe we need anime style version of CodeFormer.
