### ISSUE TITLE
rgb+depth to side-by-side picture is too slowly

### ISSUE THREAD

**Issue by lijie2160** [nagadomi/nunif#56]
how to accelebrate it?
----
resolved.

**Comment by nagadomi** [comment]
If there are no additional problems, this issue can be closed.

Possible causes for this title issue,
the first time you use a model(zoedepth,rembg,etc) it can take a long time to download it.
However, it is only needed once.

Also, iw3 loads a model file that is 1.5 GB each time it is run. So if HDD is slow, it will take more time to load a model file than it takes to process a single image.
When multiple files or videos are processed, the real processing time can be measured excluding them.
