### ISSUE TITLE
Capcha does not appear in the Edge browser.

### ISSUE THREAD

**Issue by HelderRocket** [nagadomi/nunif#57]
It is not possible to download or convert files because the Capcha does not appear. I don't have the ad blocker active, I don't have the browser enhancements active (Tracking prevention and improving site security).

![image](https://github.com/nagadomi/nunif/assets/104467221/0361aaa2-0fa2-439e-b60a-db0ed1e0320e)

**Comment by nagadomi** [comment]
I tried waifu2x.udp.jp with Edge browser and it worked.
```
Microsoft Edge
Version 116.0.1938.76
```

reCAPTCHA is lazy-loaded, so it will not appear when the server is down.
In some cases, the browser cache of the main page is displayed even though the server is down.
Try hard refresh using SHIFT+F5.

**Comment by nagadomi** [comment]
reopen if this is not a issue due to the server down problem above.

**Comment by HelderRocket** [comment]
I have tried clearing the page cache, using the key combination you suggested, but it is still the same.

![image](https://github.com/nagadomi/nunif/assets/104467221/d5c52cae-1b11-495e-ad16-a0f4b6508427)

And when I hit the download or convert buttons, this comes up.

![image](https://github.com/nagadomi/nunif/assets/104467221/70fe8ca2-f18f-4e6e-b824-e123891ca3ef)

**Comment by nagadomi** [comment]
It looks like javascript is not working.
What error messages are you getting?
![edge_show_errors](https://github.com/nagadomi/nunif/assets/287255/0fa72b62-9f3e-4c12-8047-13cafe66974b)

**Comment by nagadomi** [comment]
I have tested with Edge Browser on Windows and Linux and both works.
So I am guessing that the problem may be with your network or browser extensions or settings.

**Comment by HelderRocket** [comment]
I know what the problem is. It's because of the Adblock ad blocker. Despite having it set to not act on the page, it somehow blocks the Capcha.

I just found out, since I tried to disable that extension.

However, I will show you below the error messages that appear with the extensions enabled:

![image](https://github.com/nagadomi/nunif/assets/104467221/63e7d5d4-0cd6-46fc-a567-552cf2c1acf4)

![image](https://github.com/nagadomi/nunif/assets/104467221/cbc24a30-854c-4e5f-ab8b-5a8efba5984c)

![image](https://github.com/nagadomi/nunif/assets/104467221/992d8f2e-1d42-4b4b-b32c-3d57aa9bd46c)

![image](https://github.com/nagadomi/nunif/assets/104467221/af25d842-7ae8-4531-930d-a80500df2bf4)

![image](https://github.com/nagadomi/nunif/assets/104467221/620432f4-c457-448b-9806-071817ac4ab1)

![image](https://github.com/nagadomi/nunif/assets/104467221/a787fbdb-9f39-4606-ab60-670e80f83667)

![image](https://github.com/nagadomi/nunif/assets/104467221/329344e9-1119-4739-bed8-89541fdac8d8)

**Comment by nagadomi** [comment]
In that case, report the bug to that Adblock extension, not here.
