### ISSUE TITLE
unlimited.waifu2x.net无法使用

### ISSUE THREAD

**Issue by yuxigu5254** [nagadomi/nunif#61]
https://unlimited.waifu2x.net/网站不能用了吗，换了好几个浏览器，只有alook浏览器可以处理成功(但是下载会报错)
![Screenshot_2023-10-13-17-27-21-880_alook browser](https://github.com/nagadomi/nunif/assets/139209638/70eecbe2-788d-4479-9278-485eb673ed58)
![Screenshot_2023-10-13-17-27-34-309_alook browser](https://github.com/nagadomi/nunif/assets/139209638/7b6e4d02-4c37-4ea9-8188-17e03249bc04)
其他几个浏览器一直是处理中
![7a16036b1865a8d4](https://github.com/nagadomi/nunif/assets/139209638/ed3abfea-984e-45e0-bc4b-68fb3313ab26)

**Comment by nagadomi** [comment]
It works with standard Google Chrome browser.
If the errors occur only with large files, it may be the memory limit of the device.

**Comment by nagadomi** [comment]
>Can not handle uri:: blob:https://..
>Excepted URL scheme 'http' or "https'

These browsers likely do not support Blob URI scheme handling.
It is not implemented in WebView, so it needs to be implemented on the browser app side.
You should report this to browser developers.
