### ISSUE TITLE
Custom upscale values?

### ISSUE THREAD

**Issue by watatomo** [nagadomi/nunif#62]
It would be wonderful if there was a way for us to use custom upscale values side from the 1.6x/2x/4x provided. I use this to upscale manga pages and I want them to be in a specific resolution while retaining the highest quality possible. I could downscale the images, but that can lead to a decrease in quality. Being able to input our own values would give us the best result. 1.6x can sometimes make the pages bigger than what I want them to be (e.g. I have a page that's 1131x1609 px. I want it to be 1350x1920 pixels. 1.6x would give me 1809x2574 pixels.)

**Comment by nagadomi** [comment]
Currently, waifu2x supports only three fixed scale values: 1x, 2x, and 4x.
1.6x is implemented with downscaling from 2x.
So the result is no different than when you downscale by yourself.

For manga downscaling,
there is a problem with moiré artifacts on screen tones.
In my experience, OpenCV's INTER_AREA downscaling algorithm gives the best results.
The best currently available methods are,
1. 4x with art/scan model (art/scan 2x is downscaled model, 4x is the original upscaling result)
2. Downscaling to arbitrary size with OpenCV's INTER_AREA

**Comment by watatomo** [comment]
That's very useful. I'll keep it in mind. Thank you for your reply!

**Comment by watatomo** [comment]
Oops. I forgot to mention this. There are some cases where the `art` model works better than the `art/scan` model as some artifacts get lost. Here's an example: https://slow.pics/c/HEKzFEvo

**Comment by nagadomi** [comment]
When using `art` model, 2x is also the original upscaling result. Only `art/scan` and `photo` are downscaled from 4x.

On average, I try to achieve better results with art/scan for screentones, but there are some bad cases.
`art` model is only trained for JPEG noise, while `art/scan` model supports many noise caused by scanners, printers, and papers. So more details may lost.
