### ISSUE TITLE
What will be the installation process if I only want to use waifu2x?

### ISSUE THREAD

**Issue by AntsyLich** [nagadomi/nunif#63]

**Comment by nagadomi** [comment]
1. normal installation
2. delete `iw3/pretrained_models/hub` if it is installed from `windows_package`

**Comment by nagadomi** [comment]
I am not sure what part of the normal installation you find a problem.
Above, I responded assuming that you are complaining about the file size of the pretrained-models you do not use.

For using waifu2x as a library, see [Python API(torch.hub)](https://github.com/nagadomi/nunif/blob/master/waifu2x/docs/python_api.md).
For programming languages other than Python, ONNX can be used; see [unlimited:waifu2x](https://github.com/nagadomi/nunif/tree/master/waifu2x/unlimited_waifu2x) for a javascript example.

If it is any other issue, please describe in detail.
If nothing else, I will close this issue.
