### ISSUE TITLE
How to make a local server global?

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#65]
- [ ] Add a global server capability.

**Comment by nagadomi** [comment]
There are two ways to do this:

#### `--bind-addr 0.0.0.0` option

```
--bind-addr BIND_ADDR
                        0.0.0.0 for global, 127.0.0.1 for local (default: 127.0.0.1)
```

It simply accepts access from all IP addresses to waifu2x.web instance.
You need to open the port by setting up router, firewall, etc.

This method is useful for small public access. For example, only a few friends have access.

#### nginx reverse proxy

waifu2x.udp.jp is managed in this way.
The advantage is that static files can be served directly from `public_html/` file system.

An example setting can be found in https://github.com/nagadomi/nunif/tree/master/waifu2x/web/appendix .

**Comment by nagadomi** [comment]
I added docs on this. https://github.com/nagadomi/nunif/commit/c65574e1df29444340bc43c6dc5495ec384005ce

**Comment by My12123** [comment]
@nagadomi It didn't help.
![2023-11-09_12-44-57](https://github.com/nagadomi/nunif/assets/49092250/211b729c-66a3-447f-a1f5-87a6d4b52dbe)
![2023-11-09_12-44-29](https://github.com/nagadomi/nunif/assets/49092250/a945f7a3-6bf3-47f3-aa24-9ae52e58ecca)

**Comment by nagadomi** [comment]
@My12123 
"http://0.0.0.0/" works on Linux and macOS, but not on Windows.
It is just a URL print problem of the http server library. 
Use "http://127.0.0.1:8812" even if "--bind-addr 0.0.0.0" is specified.
