### ISSUE TITLE
Add an option with the same file name as the original one during batch processing.

### ISSUE THREAD

**Issue by My12123** [nagadomi/nunif#67]
- [ ] Add an option with the same file name as the original one during batch processing.

**Comment by nagadomi** [comment]
If you specify a directory as output, it will be output with the original filename (basename).
This is basic batch processing behavior.  It never outputs with different filename.

Or are you talking about image format? (jpg, png, webp)

**Comment by My12123** [comment]
Is it possible to save a file in the same format during batch processing as the original nadine of one format of another of another, and 3 of another?

![2023-11-14_16-38-47](https://github.com/nagadomi/nunif/assets/49092250/561993eb-a3dd-4b9a-aa1d-4ead44484460)
![2023-11-14_16-38-24](https://github.com/nagadomi/nunif/assets/49092250/51b344bd-e545-4767-8f3f-90844963b500)

- [ ] The ability to replace photos. From source to output. Add an argument preferably short -

**Comment by nagadomi** [comment]
With so many image formats, it is impossible to support all format output.
Without doing that, this feature cannot be implemented correctly, so I will not implement it.

You can specify the output format with `--format` option (jpg png webp).
