### ISSUE TITLE
About swin unet's version

### ISSUE THREAD

**Issue by 98mxr** [nagadomi/nunif#7]
Why choose swin_transformer_v1 instead of v2?

**Comment by nagadomi** [comment]
Actually, I haven't tried many experiments. I am still trying things out.
The reason for using V1 now is simply because V2 is slow and many other swin transformer based models use V1.

**Comment by 98mxr** [comment]
I understand, the paper mentions that v2 may adapt better to different size inputs, looking forward to the good news from your side.
