### ISSUE TITLE
Instructions?

### ISSUE THREAD

**Issue by arthurwolf** [nagadomi/nunif#72]
I don't understand the ReadMe, it doesn't seem to contain instructions on runningthis.

I found this repo because I was trying to run Waifu2x but it's clearly outdated (broken links, ubuntu 16.04 etc), and at the top of its readme it points to here as a more recent version.

But then when I get here, I have no idea what to do.

I just want to get this to run and convert images, how can I do that?

I found https://github.com/nagadomi/nunif/blob/master/waifu2x/README.md but running the first command.

```
python -m waifu2x.download_models
```

I get:

```
╭─arthur at aquarelle in ~/dev/ai/manga 23-11-30 - 2:17:36
╰─○ python -m waifu2x.download_models
/home/arthur/.pyenv/versions/3.11.6/bin/python: Error while finding module specification for 'waifu2x.download_models' (ModuleNotFoundError: No module named 'waifu2x')
╭─arthur at aquarelle in ~/dev/ai/manga 23-11-30 - 2:22:05
╰─○ pip install waifu2x              
Collecting waifu2x
  Downloading waifu2x-2023-py3-none-any.whl.metadata (10 kB)
Collecting Pillow<10,>=9.0.0 (from waifu2x)
[ ... cut for brievity ... ]
Successfully installed Pillow-9.5.0 Wand-0.6.13 chainer-7.8.1 protobuf-4.25.1 six-1.16.0 waifu2x-2023
╭─arthur at aquarelle in ~/dev/ai/manga 23-11-30 - 2:22:30
╰─○ python -m waifu2x.download_models
/home/arthur/.pyenv/versions/3.11.6/bin/python: No module named waifu2x.download_models
╭─arthur at aquarelle in ~/dev/ai/manga 23-11-30 - 2:22:43
╰─○ pip install waifu2x.download_models
ERROR: Could not find a version that satisfies the requirement waifu2x.download_models (from versions: none)
ERROR: No matching distribution found for waifu2x.download_models
╭─arthur at aquarelle in ~/dev/ai/manga 23-11-30 - 2:22:53
╰─○ 
```

Thanks!!

**Comment by nagadomi** [comment]
pip waifu2x is unrelated to this project.

[INSTALL-ubuntu](https://github.com/nagadomi/nunif/blob/master/INSTALL-ubuntu.md)
[INSTALL-windows](https://github.com/nagadomi/nunif/blob/master/INSTALL-windows.md)
[INSTALL-mac](https://github.com/nagadomi/nunif/blob/master/INSTALL-mac.md)

**Comment by arthurwolf** [comment]
> pip waifu2x is unrelated to this project.
> 
> [INSTALL-ubuntu](https://github.com/nagadomi/nunif/blob/master/INSTALL-ubuntu.md) [INSTALL-windows](https://github.com/nagadomi/nunif/blob/master/INSTALL-windows.md) [INSTALL-mac](https://github.com/nagadomi/nunif/blob/master/INSTALL-mac.md)

yes I ended up finding the links at the very bottom of the readme, which is why I closed the ticket.
maybe use a bit more traditional structure for the docs, as it is now it makes it very unintuitive to figure out what to do

really cool project
