### ISSUE TITLE
iw3 only cpu

### ISSUE THREAD

**Issue by wangchuanzhang** [nagadomi/nunif#74]
Why is only the CPU recognized here and not my GPU? The CPU can be used, but it's too slow.
![屏幕截图 2024-01-26 043910](https://github.com/nagadomi/nunif/assets/89728704/064115d1-64fd-4092-a9e1-a9338c7ef8db)
![屏幕截图 2024-01-26 043911](https://github.com/nagadomi/nunif/assets/89728704/81065139-e723-4ceb-bfc8-4285e0b33eaa)

**Comment by nagadomi** [comment]
Is the same `venv` used for GUI commands and command prompts?
If you run the GUI from that command prompt, GPU still doesn't show up?
```
python -m iw3.gui
```

In the code of iw3/gui.py, it uses `torch.cuda.is_available()`,`torch.cuda.device_count()` same as the screencapture above.
https://github.com/nagadomi/nunif/blob/201fe41c0f8accca85b91cf9fe5e8edd62a802d2/iw3/gui.py#L343-L354

**Comment by nagadomi** [comment]
Other causes than venv,
There may be multiple Python (Offical Python, Anaconda) installed and `pythonw` command used in the bat file point to a different environment.

**Comment by wangchuanzhang** [comment]
> Other causes than venv, There may be multiple Python (Offical Python, Anaconda) installed and `pythonw` command used in the bat file point to a different environment.

Thank you for your response! The issue has been resolved, and it was due to multiple Python.  IW3 is amazing！ Keep up the good work!

**Comment by nagadomi** [comment]
Good to see that this issue was resolved quickly.
In dev branch, you can use the recently released [DepthAnything](https://github.com/LiheYoung/Depth-Anything) model.
I haven't tried it much yet, so I am not sure if it is better suited than ZoeDepth, though.
