### ISSUE TITLE
How to use command run this?

### ISSUE THREAD

**Issue by lp20010415** [nagadomi/nunif#79]
I want use nunif in the google colab. So I want know how to use command run nunif.

**Comment by nagadomi** [comment]
For waifu2x command line interface, see https://github.com/nagadomi/nunif/blob/master/waifu2x/docs/cli.md

For iw3 cli, see the help message `python -m iw3.cli -h`.
A basic example is 
```
python -m iw3.cli --depth-model Any_B --zoed-batch-size 4  -i ./input.mp4 -o ./output_dir --yes
```

**Comment by lp20010415** [comment]
> For waifu2x command line interface, see https://github.com/nagadomi/nunif/blob/master/waifu2x/docs/cli.md
> 
> For iw3 cli, see the help message `python -m iw3.cli -h`. A basic example is
> 
> ```
> python -m iw3.cli --depth-model Any_B --zoed-batch-size 4  -i ./input.mp4 -o ./output_dir --resume
> ```
> 
> `--resume`: Skip if output file exists. `--yes`: Overwrite the output file if it exists.

Ok,thanks.
