### ISSUE TITLE
Iw3 edits on discord

### ISSUE THREAD

**Issue by loawizard** [nagadomi/nunif#81]
Hello!

First of all, thank you so much for making this amazing software available for everyone!
It's truly amazing.

me and a group of 2D to 3D fanatics have created some edits to the gui and utils files to unlock it even more!
We have created a discord where we test out Iw3 on different PC setups, and we would be honoured if you could join.

We want to help you improve Iw3 so it becomes the best 2D to 3D converter ever! Also, I can make you the co-owner of the Discord, as it is your software!

Here is the link to the discord : https://discord.gg/T72KQJ6z

Thank you so much, and I hope to talk to you soon.

**Comment by nagadomi** [comment]
https://github.com/nagadomi/nunif/discussions/80
