### ISSUE TITLE
Where is scale2x.pth?

### ISSUE THREAD

**Issue by noriwaru** [nagadomi/nunif#9]
The following code was executed in colab.
>!python -m waifu2x.web
>FileNotFoundError: [Errno 2] No such file or directory: '/content/nunif/waifu2x/pretrained_models/swin_unet/art/scale2x.pth'

How can I get the file scale2x.pth?
Can't I use it with COLAB in the first place?

**Comment by nagadomi** [comment]
from [README](https://github.com/nagadomi/nunif/blob/master/waifu2x/README.md)
>Download pre-trained models.
>`python -m waifu2x.download_models`
>This command downloads the pre-trained models to `waifu2x/pretrained_models`.

You can also download it manually from the link in the Release section.
https://github.com/nagadomi/nunif/releases/tag/0.0.0 (waifu2x_pretrained_models_20230202.zip)

**Comment by nagadomi** [comment]
I tried waifu2x.web with Colab. It seems to work.

Install
```
!git clone https://github.com/nagadomi/nunif
%cd nunif
!pip3 install -r requirements.txt
!python -m waifu2x.download_models
!python -m waifu2x.web.webgen.gen
```

Running waifu2x.web as a background task (larger image size limit)
```
!mkdir -p tmp/
!python -m waifu2x.web --port 8812 --max-pixels 16777216 --max-body-size 100 > ./tmp/server.log 2>&1 & 
```

Show inline Web UI on Colab notebook
```
from google.colab import output
output.serve_kernel_port_as_iframe(8812, "")
```

**Comment by noriwaru** [comment]
Thank you very much. It worked. Sorry for the late reply. It was very helpful.
